<?xml version="1.0" encoding="utf-8"?><Database Name="part" Class="PartSearchDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=part;Integrated Security=True" SettingsObjectName="CprBroker.Providers.Local.Search.Properties.Settings" SettingsPropertyName="partConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PersonSearchCache" Member="PersonSearchCaches">
    <Type Name="PersonSearchCache">
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LivscyklusKode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="AddressingName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PersonGivenName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PersonMiddleName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PersonSurnameName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PersonGenderCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FoedestedNavn" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FoedselsregistreringMyndighedNavn" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserInterfaceKeyText" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PersonCivilRegistrationIdentifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PersonNummerGyldighedStatusIndikator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PersonNationalityCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NavneAdresseBeskyttelseIndikator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TelefonNummerBeskyttelseIndikator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ForskerBeskyttelseIndikator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdresseNoteTekst" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FolkekirkeMedlemIndikator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoteTekst_DanskAdresse" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UkendtAdresseIndikator" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SpecielVejkodeIndikator" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PostDistriktTekst" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MunicipalityCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StreetCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StreetBuildingIdentifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MailDeliverySublocationIdentifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StreetName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StreetNameForAddressingName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StreetBuildingIdentifier_Postal" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FloorIdentifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SuiteIdentifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DistrictSubdivisionIdentifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PostOfficeBoxIdentifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PostCodeIdentifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CountryIdentificationCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>