<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://serviceplatformen.dk/xml/wsdl/soap11/CprService/1/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	targetNamespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprService/1/" 
	name="CprService">
	<types>
		<xsd:schema targetNamespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprService/1/">
			<xsd:include schemaLocation="CprServiceMsg.xsd" />
		</xsd:schema>
	</types>

	<message name="forwardToCPRServiceRequest">
		<part name="parameters" element="tns:forwardToCPRServiceRequest" />
	</message>
	
	<message name="forwardToCPRServiceResponse">
		<part name="parameters" element="tns:forwardToCPRServiceResponse" />
	</message>

	<portType name="CprServicePortType">

    <operation name="forwardToCPRService">
	  <input message="tns:forwardToCPRServiceRequest" />
	  <output message="tns:forwardToCPRServiceResponse" />
	</operation>
	
	</portType>

	<binding name="CprBinding" type="tns:CprServicePortType">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />

		<operation name="forwardToCPRService">
		  	<soap:operation soapAction=""/>
				<input>
				<soap:body use="literal" />		 
				</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>

	</binding>

	<service name="CprService">
		<port name="CprServicePort" binding="tns:CprBinding">
			<soap:address location="http://localhost:8080/CPRWebService/CprService" />
		</port>
	</service>
</definitions>
