DECLARE @SQL VARCHAR(MAX)
DECLARE @Id INT

BEGIN TRY
	--BEGIN TRANSACTION 
	
	SET @SQL = ''
	
	DECLARE SqlCursor CURSOR	
	FOR SELECT ID, SQL FROM _InstallerSql	ORDER BY ID

	OPEN SqlCursor
	FETCH NEXT FROM SqlCursor INTO @Id, @SQL

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF SUBSTRING(@SQL, 1, LEN('INSERT')) = 'INSERT'
		BEGIN
			BEGIN TRY
				EXEC (@SQL)
			END TRY
			BEGIN CATCH
			END CATCH
		END
		ELSE
		BEGIN
			EXEC (@SQL)
		END
		
		UPDATE _InstallerSql SET ExecutionDate = GETDATE() WHERE ID=@ID
		FETCH NEXT FROM SqlCursor INTO @Id, @SQL
	END

	CLOSE SqlCursor
	DEALLOCATE SqlCursor

	--COMMIT
END TRY

BEGIN CATCH
	--IF @@TRANCOUNT > 0
	--	ROLLBACK 

	DECLARE @ErrMsg nvarchar(4000), @ErrSeverity int
	SELECT @ErrMsg = ERROR_MESSAGE(), @ErrSeverity = ERROR_SEVERITY()

	RAISERROR(@ErrMsg, @ErrSeverity, 1)
END CATCH
