<?xml version="1.0" encoding="utf-8"?><Database Name="CPRDirect" EntityNamespace="CprBroker.Providers.CPRDirect" ContextNamespace="CprBroker.Providers.CPRDirect" Class="ExtractDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=CPRDirect;Integrated Security=True" SettingsObjectName="CprBroker.Providers.CPRDirect.Properties.Settings" SettingsPropertyName="CPRDirectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Extract" Member="Extracts">
    <Type Name="Extract">
      <Column Name="ExtractId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExtractDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="StartRecord" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EndRecord" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Extract_ExtractItem" Member="ExtractItems" ThisKey="ExtractId" OtherKey="ExtractId" Type="ExtractItem" />
    </Type>
  </Table>
  <Table Name="dbo.ExtractItem" Member="ExtractItems">
    <Type Name="ExtractItem">
      <Column Name="ExtractItemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExtractId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CprNumber" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DataTypeCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Contents" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Extract_ExtractItem" Member="Extract" ThisKey="ExtractId" OtherKey="ExtractId" Type="Extract" IsForeignKey="true" />
    </Type>
  </Table>
</Database>