#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CprBroker.Data.DataProviders
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PART")]
	public partial class DataProvidersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDataProvider(DataProvider instance);
    partial void UpdateDataProvider(DataProvider instance);
    partial void DeleteDataProvider(DataProvider instance);
    partial void InsertBudgetInterval(BudgetInterval instance);
    partial void UpdateBudgetInterval(BudgetInterval instance);
    partial void DeleteBudgetInterval(BudgetInterval instance);
    #endregion
		
		public DataProvidersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProvidersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProvidersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProvidersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DataProvider> DataProviders
		{
			get
			{
				return this.GetTable<DataProvider>();
			}
		}
		
		public System.Data.Linq.Table<BudgetInterval> BudgetIntervals
		{
			get
			{
				return this.GetTable<BudgetInterval>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DataProvider")]
	public partial class DataProvider : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DataProviderId;
		
		private string _TypeName;
		
		private int _Ordinal;
		
		private System.Data.Linq.Binary _Data;
		
		private bool _IsExternal;
		
		private bool _IsEnabled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDataProviderIdChanging(System.Guid value);
    partial void OnDataProviderIdChanged();
    partial void OnTypeNameChanging(string value);
    partial void OnTypeNameChanged();
    partial void OnOrdinalChanging(int value);
    partial void OnOrdinalChanged();
    partial void OnDataChanging(System.Data.Linq.Binary value);
    partial void OnDataChanged();
    partial void OnIsExternalChanging(bool value);
    partial void OnIsExternalChanged();
    partial void OnIsEnabledChanging(bool value);
    partial void OnIsEnabledChanged();
    #endregion
		
		public DataProvider()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataProviderId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DataProviderId
		{
			get
			{
				return this._DataProviderId;
			}
			set
			{
				if ((this._DataProviderId != value))
				{
					this.OnDataProviderIdChanging(value);
					this.SendPropertyChanging();
					this._DataProviderId = value;
					this.SendPropertyChanged("DataProviderId");
					this.OnDataProviderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this.OnTypeNameChanging(value);
					this.SendPropertyChanging();
					this._TypeName = value;
					this.SendPropertyChanged("TypeName");
					this.OnTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordinal", DbType="Int NOT NULL")]
		public int Ordinal
		{
			get
			{
				return this._Ordinal;
			}
			set
			{
				if ((this._Ordinal != value))
				{
					this.OnOrdinalChanging(value);
					this.SendPropertyChanging();
					this._Ordinal = value;
					this.SendPropertyChanged("Ordinal");
					this.OnOrdinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsExternal", DbType="Bit NOT NULL")]
		public bool IsExternal
		{
			get
			{
				return this._IsExternal;
			}
			set
			{
				if ((this._IsExternal != value))
				{
					this.OnIsExternalChanging(value);
					this.SendPropertyChanging();
					this._IsExternal = value;
					this.SendPropertyChanged("IsExternal");
					this.OnIsExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnabled", DbType="Bit NOT NULL")]
		public bool IsEnabled
		{
			get
			{
				return this._IsEnabled;
			}
			set
			{
				if ((this._IsEnabled != value))
				{
					this.OnIsEnabledChanging(value);
					this.SendPropertyChanging();
					this._IsEnabled = value;
					this.SendPropertyChanged("IsEnabled");
					this.OnIsEnabledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BudgetInterval")]
	public partial class BudgetInterval : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IntervalMillisecods;
		
		private string _Name;
		
		private System.Nullable<int> _CallThreshold;
		
		private System.Nullable<decimal> _CostThreshold;
		
		private System.Nullable<System.DateTime> _LastChecked;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIntervalMillisecodsChanging(long value);
    partial void OnIntervalMillisecodsChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCallThresholdChanging(System.Nullable<int> value);
    partial void OnCallThresholdChanged();
    partial void OnCostThresholdChanging(System.Nullable<decimal> value);
    partial void OnCostThresholdChanged();
    partial void OnLastCheckedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCheckedChanged();
    #endregion
		
		public BudgetInterval()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntervalMillisecods", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IntervalMillisecods
		{
			get
			{
				return this._IntervalMillisecods;
			}
			set
			{
				if ((this._IntervalMillisecods != value))
				{
					this.OnIntervalMillisecodsChanging(value);
					this.SendPropertyChanging();
					this._IntervalMillisecods = value;
					this.SendPropertyChanged("IntervalMillisecods");
					this.OnIntervalMillisecodsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallThreshold", DbType="Int")]
		public System.Nullable<int> CallThreshold
		{
			get
			{
				return this._CallThreshold;
			}
			set
			{
				if ((this._CallThreshold != value))
				{
					this.OnCallThresholdChanging(value);
					this.SendPropertyChanging();
					this._CallThreshold = value;
					this.SendPropertyChanged("CallThreshold");
					this.OnCallThresholdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostThreshold", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> CostThreshold
		{
			get
			{
				return this._CostThreshold;
			}
			set
			{
				if ((this._CostThreshold != value))
				{
					this.OnCostThresholdChanging(value);
					this.SendPropertyChanging();
					this._CostThreshold = value;
					this.SendPropertyChanged("CostThreshold");
					this.OnCostThresholdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastChecked", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastChecked
		{
			get
			{
				return this._LastChecked;
			}
			set
			{
				if ((this._LastChecked != value))
				{
					this.OnLastCheckedChanging(value);
					this.SendPropertyChanging();
					this._LastChecked = value;
					this.SendPropertyChanged("LastChecked");
					this.OnLastCheckedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
