<?xml version="1.0" encoding="utf-8"?><Database Name="PART" EntityNamespace="CprBroker.Providers.CPRDirect" ContextNamespace="CprBroker.Providers.CPRDirect" Class="LookupDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Authority" Member="Authorities">
    <Type Name="Authority">
      <Column Name="AuthorityCode" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AuthorityType" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorityGroup" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AuthorityPhone" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AuthorityName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="AddressLine2" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="AddressLine3" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="AddressLine4" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="Telefax" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Alpha2CountryCode" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Alpha3CountryCode" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="NumericCountryCode" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>