#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CprBroker.Providers.CPRDirect
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DPR")]
	public partial class LookupDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAuthority(Authority instance);
    partial void UpdateAuthority(Authority instance);
    partial void DeleteAuthority(Authority instance);
    partial void InsertPostDistrict(PostDistrict instance);
    partial void UpdatePostDistrict(PostDistrict instance);
    partial void DeletePostDistrict(PostDistrict instance);
    partial void InsertStreet(Street instance);
    partial void UpdateStreet(Street instance);
    partial void DeleteStreet(Street instance);
    partial void InsertCity(City instance);
    partial void UpdateCity(City instance);
    partial void DeleteCity(City instance);
    partial void InsertAreaRestorationDistrict(AreaRestorationDistrict instance);
    partial void UpdateAreaRestorationDistrict(AreaRestorationDistrict instance);
    partial void DeleteAreaRestorationDistrict(AreaRestorationDistrict instance);
    partial void InsertDiverseDistrict(DiverseDistrict instance);
    partial void UpdateDiverseDistrict(DiverseDistrict instance);
    partial void DeleteDiverseDistrict(DiverseDistrict instance);
    partial void InsertChurchAdministrationDistrict(ChurchAdministrationDistrict instance);
    partial void UpdateChurchAdministrationDistrict(ChurchAdministrationDistrict instance);
    partial void DeleteChurchAdministrationDistrict(ChurchAdministrationDistrict instance);
    partial void InsertPopulationDistrict(PopulationDistrict instance);
    partial void UpdatePopulationDistrict(PopulationDistrict instance);
    partial void DeletePopulationDistrict(PopulationDistrict instance);
    partial void InsertEvacuationDistrict(EvacuationDistrict instance);
    partial void UpdateEvacuationDistrict(EvacuationDistrict instance);
    partial void DeleteEvacuationDistrict(EvacuationDistrict instance);
    partial void InsertSchoolDistrict(SchoolDistrict instance);
    partial void UpdateSchoolDistrict(SchoolDistrict instance);
    partial void DeleteSchoolDistrict(SchoolDistrict instance);
    partial void InsertSocialDistrict(SocialDistrict instance);
    partial void UpdateSocialDistrict(SocialDistrict instance);
    partial void DeleteSocialDistrict(SocialDistrict instance);
    partial void InsertChurchDistrict(ChurchDistrict instance);
    partial void UpdateChurchDistrict(ChurchDistrict instance);
    partial void DeleteChurchDistrict(ChurchDistrict instance);
    partial void InsertElectionDistrict(ElectionDistrict instance);
    partial void UpdateElectionDistrict(ElectionDistrict instance);
    partial void DeleteElectionDistrict(ElectionDistrict instance);
    partial void InsertHeatingDistrict(HeatingDistrict instance);
    partial void UpdateHeatingDistrict(HeatingDistrict instance);
    partial void DeleteHeatingDistrict(HeatingDistrict instance);
    partial void InsertPostNumber(PostNumber instance);
    partial void UpdatePostNumber(PostNumber instance);
    partial void DeletePostNumber(PostNumber instance);
    partial void InsertCouncil(Council instance);
    partial void UpdateCouncil(Council instance);
    partial void DeleteCouncil(Council instance);
    #endregion
		
		public LookupDataContext() : 
				base(global::CprBroker.Providers.CPRDirect.Properties.Settings.Default.DPRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LookupDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Authority> Authorities
		{
			get
			{
				return this.GetTable<Authority>();
			}
		}
		
		public System.Data.Linq.Table<PostDistrict> PostDistricts
		{
			get
			{
				return this.GetTable<PostDistrict>();
			}
		}
		
		public System.Data.Linq.Table<Street> Streets
		{
			get
			{
				return this.GetTable<Street>();
			}
		}
		
		public System.Data.Linq.Table<City> Cities
		{
			get
			{
				return this.GetTable<City>();
			}
		}
		
		public System.Data.Linq.Table<AreaRestorationDistrict> AreaRestorationDistricts
		{
			get
			{
				return this.GetTable<AreaRestorationDistrict>();
			}
		}
		
		public System.Data.Linq.Table<DiverseDistrict> DiverseDistricts
		{
			get
			{
				return this.GetTable<DiverseDistrict>();
			}
		}
		
		public System.Data.Linq.Table<ChurchAdministrationDistrict> ChurchAdministrationDistricts
		{
			get
			{
				return this.GetTable<ChurchAdministrationDistrict>();
			}
		}
		
		public System.Data.Linq.Table<PopulationDistrict> PopulationDistricts
		{
			get
			{
				return this.GetTable<PopulationDistrict>();
			}
		}
		
		public System.Data.Linq.Table<EvacuationDistrict> EvacuationDistricts
		{
			get
			{
				return this.GetTable<EvacuationDistrict>();
			}
		}
		
		public System.Data.Linq.Table<SchoolDistrict> SchoolDistricts
		{
			get
			{
				return this.GetTable<SchoolDistrict>();
			}
		}
		
		public System.Data.Linq.Table<SocialDistrict> SocialDistricts
		{
			get
			{
				return this.GetTable<SocialDistrict>();
			}
		}
		
		public System.Data.Linq.Table<ChurchDistrict> ChurchDistricts
		{
			get
			{
				return this.GetTable<ChurchDistrict>();
			}
		}
		
		public System.Data.Linq.Table<ElectionDistrict> ElectionDistricts
		{
			get
			{
				return this.GetTable<ElectionDistrict>();
			}
		}
		
		public System.Data.Linq.Table<HeatingDistrict> HeatingDistricts
		{
			get
			{
				return this.GetTable<HeatingDistrict>();
			}
		}
		
		public System.Data.Linq.Table<PostNumber> PostNumbers
		{
			get
			{
				return this.GetTable<PostNumber>();
			}
		}
		
		public System.Data.Linq.Table<Council> Councils
		{
			get
			{
				return this.GetTable<Council>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Authority")]
	public partial class Authority : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AuthorityCode;
		
		private string _AuthorityType;
		
		private string _AuthorityGroup;
		
		private System.DateTime _UpdateTime;
		
		private string _AuthorityPhone;
		
		private System.DateTime _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _AuthorityName;
		
		private string _Address;
		
		private string _AddressLine1;
		
		private string _AddressLine2;
		
		private string _AddressLine3;
		
		private string _AddressLine4;
		
		private string _Telefax;
		
		private string _FullName;
		
		private string _Email;
		
		private string _Alpha2CountryCode;
		
		private string _Alpha3CountryCode;
		
		private string _NumericCountryCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuthorityCodeChanging(string value);
    partial void OnAuthorityCodeChanged();
    partial void OnAuthorityTypeChanging(string value);
    partial void OnAuthorityTypeChanged();
    partial void OnAuthorityGroupChanging(string value);
    partial void OnAuthorityGroupChanged();
    partial void OnUpdateTimeChanging(System.DateTime value);
    partial void OnUpdateTimeChanged();
    partial void OnAuthorityPhoneChanging(string value);
    partial void OnAuthorityPhoneChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnAuthorityNameChanging(string value);
    partial void OnAuthorityNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAddressLine1Changing(string value);
    partial void OnAddressLine1Changed();
    partial void OnAddressLine2Changing(string value);
    partial void OnAddressLine2Changed();
    partial void OnAddressLine3Changing(string value);
    partial void OnAddressLine3Changed();
    partial void OnAddressLine4Changing(string value);
    partial void OnAddressLine4Changed();
    partial void OnTelefaxChanging(string value);
    partial void OnTelefaxChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAlpha2CountryCodeChanging(string value);
    partial void OnAlpha2CountryCodeChanged();
    partial void OnAlpha3CountryCodeChanging(string value);
    partial void OnAlpha3CountryCodeChanged();
    partial void OnNumericCountryCodeChanging(string value);
    partial void OnNumericCountryCodeChanged();
    #endregion
		
		public Authority()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorityCode", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AuthorityCode
		{
			get
			{
				return this._AuthorityCode;
			}
			set
			{
				if ((this._AuthorityCode != value))
				{
					this.OnAuthorityCodeChanging(value);
					this.SendPropertyChanging();
					this._AuthorityCode = value;
					this.SendPropertyChanged("AuthorityCode");
					this.OnAuthorityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorityType", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string AuthorityType
		{
			get
			{
				return this._AuthorityType;
			}
			set
			{
				if ((this._AuthorityType != value))
				{
					this.OnAuthorityTypeChanging(value);
					this.SendPropertyChanging();
					this._AuthorityType = value;
					this.SendPropertyChanged("AuthorityType");
					this.OnAuthorityTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorityGroup", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string AuthorityGroup
		{
			get
			{
				return this._AuthorityGroup;
			}
			set
			{
				if ((this._AuthorityGroup != value))
				{
					this.OnAuthorityGroupChanging(value);
					this.SendPropertyChanging();
					this._AuthorityGroup = value;
					this.SendPropertyChanged("AuthorityGroup");
					this.OnAuthorityGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorityPhone", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string AuthorityPhone
		{
			get
			{
				return this._AuthorityPhone;
			}
			set
			{
				if ((this._AuthorityPhone != value))
				{
					this.OnAuthorityPhoneChanging(value);
					this.SendPropertyChanging();
					this._AuthorityPhone = value;
					this.SendPropertyChanged("AuthorityPhone");
					this.OnAuthorityPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorityName", DbType="NVarChar(20)")]
		public string AuthorityName
		{
			get
			{
				return this._AuthorityName;
			}
			set
			{
				if ((this._AuthorityName != value))
				{
					this.OnAuthorityNameChanging(value);
					this.SendPropertyChanging();
					this._AuthorityName = value;
					this.SendPropertyChanged("AuthorityName");
					this.OnAuthorityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(34)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine1", DbType="NVarChar(34)")]
		public string AddressLine1
		{
			get
			{
				return this._AddressLine1;
			}
			set
			{
				if ((this._AddressLine1 != value))
				{
					this.OnAddressLine1Changing(value);
					this.SendPropertyChanging();
					this._AddressLine1 = value;
					this.SendPropertyChanged("AddressLine1");
					this.OnAddressLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine2", DbType="NVarChar(34)")]
		public string AddressLine2
		{
			get
			{
				return this._AddressLine2;
			}
			set
			{
				if ((this._AddressLine2 != value))
				{
					this.OnAddressLine2Changing(value);
					this.SendPropertyChanging();
					this._AddressLine2 = value;
					this.SendPropertyChanged("AddressLine2");
					this.OnAddressLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine3", DbType="NVarChar(34)")]
		public string AddressLine3
		{
			get
			{
				return this._AddressLine3;
			}
			set
			{
				if ((this._AddressLine3 != value))
				{
					this.OnAddressLine3Changing(value);
					this.SendPropertyChanging();
					this._AddressLine3 = value;
					this.SendPropertyChanged("AddressLine3");
					this.OnAddressLine3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine4", DbType="NVarChar(34)")]
		public string AddressLine4
		{
			get
			{
				return this._AddressLine4;
			}
			set
			{
				if ((this._AddressLine4 != value))
				{
					this.OnAddressLine4Changing(value);
					this.SendPropertyChanging();
					this._AddressLine4 = value;
					this.SendPropertyChanged("AddressLine4");
					this.OnAddressLine4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefax", DbType="VarChar(8)")]
		public string Telefax
		{
			get
			{
				return this._Telefax;
			}
			set
			{
				if ((this._Telefax != value))
				{
					this.OnTelefaxChanging(value);
					this.SendPropertyChanging();
					this._Telefax = value;
					this.SendPropertyChanged("Telefax");
					this.OnTelefaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(60)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alpha2CountryCode", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Alpha2CountryCode
		{
			get
			{
				return this._Alpha2CountryCode;
			}
			set
			{
				if ((this._Alpha2CountryCode != value))
				{
					this.OnAlpha2CountryCodeChanging(value);
					this.SendPropertyChanging();
					this._Alpha2CountryCode = value;
					this.SendPropertyChanged("Alpha2CountryCode");
					this.OnAlpha2CountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alpha3CountryCode", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string Alpha3CountryCode
		{
			get
			{
				return this._Alpha3CountryCode;
			}
			set
			{
				if ((this._Alpha3CountryCode != value))
				{
					this.OnAlpha3CountryCodeChanging(value);
					this.SendPropertyChanging();
					this._Alpha3CountryCode = value;
					this.SendPropertyChanged("Alpha3CountryCode");
					this.OnAlpha3CountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumericCountryCode", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string NumericCountryCode
		{
			get
			{
				return this._NumericCountryCode;
			}
			set
			{
				if ((this._NumericCountryCode != value))
				{
					this.OnNumericCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._NumericCountryCode = value;
					this.SendPropertyChanged("NumericCountryCode");
					this.OnNumericCountryCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTPOSTDIST")]
	public partial class PostDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _POSTNR;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnPOSTNRChanging(decimal value);
    partial void OnPOSTNRChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public PostDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTNR", DbType="Decimal(4,0) NOT NULL")]
		public decimal POSTNR
		{
			get
			{
				return this._POSTNR;
			}
			set
			{
				if ((this._POSTNR != value))
				{
					this.OnPOSTNRChanging(value);
					this.SendPropertyChanging();
					this._POSTNR = value;
					this.SendPropertyChanged("POSTNR");
					this.OnPOSTNRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTAKTVEJ")]
	public partial class Street : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _VEJADNVN;
		
		private string _SVEJADRNVN;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnVEJADNVNChanging(string value);
    partial void OnVEJADNVNChanged();
    partial void OnSVEJADRNVNChanging(string value);
    partial void OnSVEJADRNVNChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Street()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJADNVN", DbType="VarChar(20)")]
		public string VEJADNVN
		{
			get
			{
				return this._VEJADNVN;
			}
			set
			{
				if ((this._VEJADNVN != value))
				{
					this.OnVEJADNVNChanging(value);
					this.SendPropertyChanging();
					this._VEJADNVN = value;
					this.SendPropertyChanged("VEJADNVN");
					this.OnVEJADNVNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SVEJADRNVN", DbType="Char(20)")]
		public string SVEJADRNVN
		{
			get
			{
				return this._SVEJADRNVN;
			}
			set
			{
				if ((this._SVEJADRNVN != value))
				{
					this.OnSVEJADRNVNChanging(value);
					this.SendPropertyChanging();
					this._SVEJADRNVN = value;
					this.SendPropertyChanged("SVEJADRNVN");
					this.OnSVEJADRNVNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTBYNAVN")]
	public partial class City : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private string _BYNVN;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnBYNVNChanging(string value);
    partial void OnBYNVNChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public City()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYNVN", DbType="VarChar(34) NOT NULL", CanBeNull=false)]
		public string BYNVN
		{
			get
			{
				return this._BYNVN;
			}
			set
			{
				if ((this._BYNVN != value))
				{
					this.OnBYNVNChanging(value);
					this.SendPropertyChanging();
					this._BYNVN = value;
					this.SendPropertyChanged("BYNVN");
					this.OnBYNVNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTBYFORNYDIST")]
	public partial class AreaRestorationDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private string _BYFORNYKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnBYFORNYKODChanging(string value);
    partial void OnBYFORNYKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public AreaRestorationDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYFORNYKOD", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string BYFORNYKOD
		{
			get
			{
				return this._BYFORNYKOD;
			}
			set
			{
				if ((this._BYFORNYKOD != value))
				{
					this.OnBYFORNYKODChanging(value);
					this.SendPropertyChanging();
					this._BYFORNYKOD = value;
					this.SendPropertyChanged("BYFORNYKOD");
					this.OnBYFORNYKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTDIVDIST")]
	public partial class DiverseDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _DISTTYP;
		
		private string _DIVDISTKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnDISTTYPChanging(decimal value);
    partial void OnDISTTYPChanged();
    partial void OnDIVDISTKODChanging(string value);
    partial void OnDIVDISTKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public DiverseDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTYP", DbType="Decimal(2,0) NOT NULL")]
		public decimal DISTTYP
		{
			get
			{
				return this._DISTTYP;
			}
			set
			{
				if ((this._DISTTYP != value))
				{
					this.OnDISTTYPChanging(value);
					this.SendPropertyChanging();
					this._DISTTYP = value;
					this.SendPropertyChanged("DISTTYP");
					this.OnDISTTYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVDISTKOD", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string DIVDISTKOD
		{
			get
			{
				return this._DIVDISTKOD;
			}
			set
			{
				if ((this._DIVDISTKOD != value))
				{
					this.OnDIVDISTKODChanging(value);
					this.SendPropertyChanging();
					this._DIVDISTKOD = value;
					this.SendPropertyChanged("DIVDISTKOD");
					this.OnDIVDISTKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTSOGNEDIST")]
	public partial class ChurchAdministrationDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _MYNKOD;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnMYNKODChanging(decimal value);
    partial void OnMYNKODChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public ChurchAdministrationDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNKOD", DbType="Decimal(4,0) NOT NULL")]
		public decimal MYNKOD
		{
			get
			{
				return this._MYNKOD;
			}
			set
			{
				if ((this._MYNKOD != value))
				{
					this.OnMYNKODChanging(value);
					this.SendPropertyChanging();
					this._MYNKOD = value;
					this.SendPropertyChanged("MYNKOD");
					this.OnMYNKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTBEFOLKDIST")]
	public partial class PopulationDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private string _BEFOLKKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnBEFOLKKODChanging(string value);
    partial void OnBEFOLKKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public PopulationDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEFOLKKOD", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string BEFOLKKOD
		{
			get
			{
				return this._BEFOLKKOD;
			}
			set
			{
				if ((this._BEFOLKKOD != value))
				{
					this.OnBEFOLKKODChanging(value);
					this.SendPropertyChanging();
					this._BEFOLKKOD = value;
					this.SendPropertyChanged("BEFOLKKOD");
					this.OnBEFOLKKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTEVAKUERDIST")]
	public partial class EvacuationDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _EVAKUERKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnEVAKUERKODChanging(decimal value);
    partial void OnEVAKUERKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public EvacuationDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVAKUERKOD", DbType="Decimal(1,0) NOT NULL")]
		public decimal EVAKUERKOD
		{
			get
			{
				return this._EVAKUERKOD;
			}
			set
			{
				if ((this._EVAKUERKOD != value))
				{
					this.OnEVAKUERKODChanging(value);
					this.SendPropertyChanging();
					this._EVAKUERKOD = value;
					this.SendPropertyChanged("EVAKUERKOD");
					this.OnEVAKUERKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTSKOLEDIST")]
	public partial class SchoolDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _SKOLEKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnSKOLEKODChanging(decimal value);
    partial void OnSKOLEKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public SchoolDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKOLEKOD", DbType="Decimal(2,0) NOT NULL")]
		public decimal SKOLEKOD
		{
			get
			{
				return this._SKOLEKOD;
			}
			set
			{
				if ((this._SKOLEKOD != value))
				{
					this.OnSKOLEKODChanging(value);
					this.SendPropertyChanging();
					this._SKOLEKOD = value;
					this.SendPropertyChanged("SKOLEKOD");
					this.OnSKOLEKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTSOCIALDIST")]
	public partial class SocialDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _SOCIALKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnSOCIALKODChanging(decimal value);
    partial void OnSOCIALKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public SocialDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCIALKOD", DbType="Decimal(2,0) NOT NULL")]
		public decimal SOCIALKOD
		{
			get
			{
				return this._SOCIALKOD;
			}
			set
			{
				if ((this._SOCIALKOD != value))
				{
					this.OnSOCIALKODChanging(value);
					this.SendPropertyChanging();
					this._SOCIALKOD = value;
					this.SendPropertyChanged("SOCIALKOD");
					this.OnSOCIALKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTKIRKEDIST")]
	public partial class ChurchDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _KIRKEKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnKIRKEKODChanging(decimal value);
    partial void OnKIRKEKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public ChurchDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIRKEKOD", DbType="Decimal(2,0) NOT NULL")]
		public decimal KIRKEKOD
		{
			get
			{
				return this._KIRKEKOD;
			}
			set
			{
				if ((this._KIRKEKOD != value))
				{
					this.OnKIRKEKODChanging(value);
					this.SendPropertyChanging();
					this._KIRKEKOD = value;
					this.SendPropertyChanged("KIRKEKOD");
					this.OnKIRKEKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTVALGDIST")]
	public partial class ElectionDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _VALGKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnVALGKODChanging(decimal value);
    partial void OnVALGKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public ElectionDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALGKOD", DbType="Decimal(2,0) NOT NULL")]
		public decimal VALGKOD
		{
			get
			{
				return this._VALGKOD;
			}
			set
			{
				if ((this._VALGKOD != value))
				{
					this.OnVALGKODChanging(value);
					this.SendPropertyChanging();
					this._VALGKOD = value;
					this.SendPropertyChanged("VALGKOD");
					this.OnVALGKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTVARMEDIST")]
	public partial class HeatingDistrict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _KOMKOD;
		
		private decimal _VEJKOD;
		
		private string _HUSNRFRA;
		
		private string _HUSNRTIL;
		
		private char _LIGEULIGE;
		
		private decimal _AJFDTO;
		
		private decimal _VARMEKOD;
		
		private string _DISTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOMKODChanging(decimal value);
    partial void OnKOMKODChanged();
    partial void OnVEJKODChanging(decimal value);
    partial void OnVEJKODChanged();
    partial void OnHUSNRFRAChanging(string value);
    partial void OnHUSNRFRAChanged();
    partial void OnHUSNRTILChanging(string value);
    partial void OnHUSNRTILChanged();
    partial void OnLIGEULIGEChanging(char value);
    partial void OnLIGEULIGEChanged();
    partial void OnAJFDTOChanging(decimal value);
    partial void OnAJFDTOChanged();
    partial void OnVARMEKODChanging(decimal value);
    partial void OnVARMEKODChanged();
    partial void OnDISTTXTChanging(string value);
    partial void OnDISTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public HeatingDistrict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal KOMKOD
		{
			get
			{
				return this._KOMKOD;
			}
			set
			{
				if ((this._KOMKOD != value))
				{
					this.OnKOMKODChanging(value);
					this.SendPropertyChanging();
					this._KOMKOD = value;
					this.SendPropertyChanged("KOMKOD");
					this.OnKOMKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEJKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal VEJKOD
		{
			get
			{
				return this._VEJKOD;
			}
			set
			{
				if ((this._VEJKOD != value))
				{
					this.OnVEJKODChanging(value);
					this.SendPropertyChanging();
					this._VEJKOD = value;
					this.SendPropertyChanged("VEJKOD");
					this.OnVEJKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRFRA", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRFRA
		{
			get
			{
				return this._HUSNRFRA;
			}
			set
			{
				if ((this._HUSNRFRA != value))
				{
					this.OnHUSNRFRAChanging(value);
					this.SendPropertyChanging();
					this._HUSNRFRA = value;
					this.SendPropertyChanged("HUSNRFRA");
					this.OnHUSNRFRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSNRTIL", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string HUSNRTIL
		{
			get
			{
				return this._HUSNRTIL;
			}
			set
			{
				if ((this._HUSNRTIL != value))
				{
					this.OnHUSNRTILChanging(value);
					this.SendPropertyChanging();
					this._HUSNRTIL = value;
					this.SendPropertyChanged("HUSNRTIL");
					this.OnHUSNRTILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGEULIGE", DbType="Char(1) NOT NULL")]
		public char LIGEULIGE
		{
			get
			{
				return this._LIGEULIGE;
			}
			set
			{
				if ((this._LIGEULIGE != value))
				{
					this.OnLIGEULIGEChanging(value);
					this.SendPropertyChanging();
					this._LIGEULIGE = value;
					this.SendPropertyChanged("LIGEULIGE");
					this.OnLIGEULIGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJFDTO", DbType="Decimal(13,0) NOT NULL")]
		public decimal AJFDTO
		{
			get
			{
				return this._AJFDTO;
			}
			set
			{
				if ((this._AJFDTO != value))
				{
					this.OnAJFDTOChanging(value);
					this.SendPropertyChanging();
					this._AJFDTO = value;
					this.SendPropertyChanged("AJFDTO");
					this.OnAJFDTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VARMEKOD", DbType="Decimal(4,0) NOT NULL")]
		public decimal VARMEKOD
		{
			get
			{
				return this._VARMEKOD;
			}
			set
			{
				if ((this._VARMEKOD != value))
				{
					this.OnVARMEKODChanging(value);
					this.SendPropertyChanging();
					this._VARMEKOD = value;
					this.SendPropertyChanged("VARMEKOD");
					this.OnVARMEKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTTXT", DbType="VarChar(30)")]
		public string DISTTXT
		{
			get
			{
				return this._DISTTXT;
			}
			set
			{
				if ((this._DISTTXT != value))
				{
					this.OnDISTTXTChanging(value);
					this.SendPropertyChanging();
					this._DISTTXT = value;
					this.SendPropertyChanged("DISTTXT");
					this.OnDISTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTPOSTNR")]
	public partial class PostNumber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _POSTNR;
		
		private string _POSTTXT;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPOSTNRChanging(decimal value);
    partial void OnPOSTNRChanged();
    partial void OnPOSTTXTChanging(string value);
    partial void OnPOSTTXTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public PostNumber()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTNR", DbType="Decimal(5,0) NOT NULL")]
		public decimal POSTNR
		{
			get
			{
				return this._POSTNR;
			}
			set
			{
				if ((this._POSTNR != value))
				{
					this.OnPOSTNRChanging(value);
					this.SendPropertyChanging();
					this._POSTNR = value;
					this.SendPropertyChanged("POSTNR");
					this.OnPOSTNRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTTXT", DbType="VarChar(20)")]
		public string POSTTXT
		{
			get
			{
				return this._POSTTXT;
			}
			set
			{
				if ((this._POSTTXT != value))
				{
					this.OnPOSTTXTChanging(value);
					this.SendPropertyChanging();
					this._POSTTXT = value;
					this.SendPropertyChanged("POSTTXT");
					this.OnPOSTTXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DTMYN")]
	public partial class Council : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _MYNKOD;
		
		private decimal _MYNTYP;
		
		private decimal _MYNGRP;
		
		private string _MYNNVN;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMYNKODChanging(decimal value);
    partial void OnMYNKODChanged();
    partial void OnMYNTYPChanging(decimal value);
    partial void OnMYNTYPChanged();
    partial void OnMYNGRPChanging(decimal value);
    partial void OnMYNGRPChanged();
    partial void OnMYNNVNChanging(string value);
    partial void OnMYNNVNChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Council()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNKOD", DbType="Decimal(5,0) NOT NULL")]
		public decimal MYNKOD
		{
			get
			{
				return this._MYNKOD;
			}
			set
			{
				if ((this._MYNKOD != value))
				{
					this.OnMYNKODChanging(value);
					this.SendPropertyChanging();
					this._MYNKOD = value;
					this.SendPropertyChanged("MYNKOD");
					this.OnMYNKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNTYP", DbType="Decimal(3,0) NOT NULL")]
		public decimal MYNTYP
		{
			get
			{
				return this._MYNTYP;
			}
			set
			{
				if ((this._MYNTYP != value))
				{
					this.OnMYNTYPChanging(value);
					this.SendPropertyChanging();
					this._MYNTYP = value;
					this.SendPropertyChanged("MYNTYP");
					this.OnMYNTYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNGRP", DbType="Decimal(1,0) NOT NULL")]
		public decimal MYNGRP
		{
			get
			{
				return this._MYNGRP;
			}
			set
			{
				if ((this._MYNGRP != value))
				{
					this.OnMYNGRPChanging(value);
					this.SendPropertyChanging();
					this._MYNGRP = value;
					this.SendPropertyChanged("MYNGRP");
					this.OnMYNGRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNNVN", DbType="VarChar(20)")]
		public string MYNNVN
		{
			get
			{
				return this._MYNNVN;
			}
			set
			{
				if ((this._MYNNVN != value))
				{
					this.OnMYNNVNChanging(value);
					this.SendPropertyChanging();
					this._MYNNVN = value;
					this.SendPropertyChanged("MYNNVN");
					this.OnMYNNVNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
