//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CPRBroker.Providers.KMD.WS_AN08300 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:zsrxsd.kmd.dk:AN08300")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08300", IsNullable=false)]
    public partial class AN08300 {
        
        private SOEGEDATA inputRecordField;
        
        /// <remarks/>
        public SOEGEDATA InputRecord {
            get {
                return this.inputRecordField;
            }
            set {
                this.inputRecordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08300")]
    public partial class SOEGEDATA {
        
        private string fORNAVNField;
        
        private string eFTERNAVNField;
        
        private string sLAEGTSNAVNField;
        
        private string mELLEMNAVNField;
        
        private string sOEGENAVNField;
        
        private string sTATUSField;
        
        private string sOEGNINGField;
        
        private string kOENField;
        
        private string vEJNAVNField;
        
        private string hISTFRAField;
        
        private string hISTTILField;
        
        private string aLDERINT1Field;
        
        private string aLDERINT2Field;
        
        private string aARINT1Field;
        
        private string aARINT2Field;
        
        private string vEJKODEField;
        
        /// <remarks/>
        public string FORNAVN {
            get {
                return this.fORNAVNField;
            }
            set {
                this.fORNAVNField = value;
            }
        }
        
        /// <remarks/>
        public string EFTERNAVN {
            get {
                return this.eFTERNAVNField;
            }
            set {
                this.eFTERNAVNField = value;
            }
        }
        
        /// <remarks/>
        public string SLAEGTSNAVN {
            get {
                return this.sLAEGTSNAVNField;
            }
            set {
                this.sLAEGTSNAVNField = value;
            }
        }
        
        /// <remarks/>
        public string MELLEMNAVN {
            get {
                return this.mELLEMNAVNField;
            }
            set {
                this.mELLEMNAVNField = value;
            }
        }
        
        /// <remarks/>
        public string SOEGENAVN {
            get {
                return this.sOEGENAVNField;
            }
            set {
                this.sOEGENAVNField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string SOEGNING {
            get {
                return this.sOEGNINGField;
            }
            set {
                this.sOEGNINGField = value;
            }
        }
        
        /// <remarks/>
        public string KOEN {
            get {
                return this.kOENField;
            }
            set {
                this.kOENField = value;
            }
        }
        
        /// <remarks/>
        public string VEJNAVN {
            get {
                return this.vEJNAVNField;
            }
            set {
                this.vEJNAVNField = value;
            }
        }
        
        /// <remarks/>
        public string HISTFRA {
            get {
                return this.hISTFRAField;
            }
            set {
                this.hISTFRAField = value;
            }
        }
        
        /// <remarks/>
        public string HISTTIL {
            get {
                return this.hISTTILField;
            }
            set {
                this.hISTTILField = value;
            }
        }
        
        /// <remarks/>
        public string ALDERINT1 {
            get {
                return this.aLDERINT1Field;
            }
            set {
                this.aLDERINT1Field = value;
            }
        }
        
        /// <remarks/>
        public string ALDERINT2 {
            get {
                return this.aLDERINT2Field;
            }
            set {
                this.aLDERINT2Field = value;
            }
        }
        
        /// <remarks/>
        public string AARINT1 {
            get {
                return this.aARINT1Field;
            }
            set {
                this.aARINT1Field = value;
            }
        }
        
        /// <remarks/>
        public string AARINT2 {
            get {
                return this.aARINT2Field;
            }
            set {
                this.aARINT2Field = value;
            }
        }
        
        /// <remarks/>
        public string VEJKODE {
            get {
                return this.vEJKODEField;
            }
            set {
                this.vEJKODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08300")]
    public partial class SVARPERSONER {
        
        private string pERSONNUMMERField;
        
        private string aDRESSERINGSNAVNField;
        
        private string aDRESSEField;
        
        private string bEMAERKNINGField;
        
        /// <remarks/>
        public string PERSONNUMMER {
            get {
                return this.pERSONNUMMERField;
            }
            set {
                this.pERSONNUMMERField = value;
            }
        }
        
        /// <remarks/>
        public string ADRESSERINGSNAVN {
            get {
                return this.aDRESSERINGSNAVNField;
            }
            set {
                this.aDRESSERINGSNAVNField = value;
            }
        }
        
        /// <remarks/>
        public string ADRESSE {
            get {
                return this.aDRESSEField;
            }
            set {
                this.aDRESSEField = value;
            }
        }
        
        /// <remarks/>
        public string BEMAERKNING {
            get {
                return this.bEMAERKNINGField;
            }
            set {
                this.bEMAERKNINGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08300")]
    public partial class SVAR {
        
        private short rETURKODEField;
        
        private string rETURTEKSTField;
        
        /// <remarks/>
        public short RETURKODE {
            get {
                return this.rETURKODEField;
            }
            set {
                this.rETURKODEField = value;
            }
        }
        
        /// <remarks/>
        public string RETURTEKST {
            get {
                return this.rETURTEKSTField;
            }
            set {
                this.rETURTEKSTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:zsrxsd.kmd.dk:AN08300")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08300", IsNullable=false)]
    public partial class AN08300Response {
        
        private SVAR outputRecordField;
        
        private SVARPERSONER[] outputArrayRecordField;
        
        /// <remarks/>
        public SVAR OutputRecord {
            get {
                return this.outputRecordField;
            }
            set {
                this.outputRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OutputArrayRecord")]
        public SVARPERSONER[] OutputArrayRecord {
            get {
                return this.outputArrayRecordField;
            }
            set {
                this.outputArrayRecordField = value;
            }
        }
    }
}
