-- 21.05.2010 - Traen A/S - JEM/MBR
-- This query returns person information from DPR database.
-- The query conforms to the DPR interface documented at http://assets1.csc.com/dpr/downloads/DPR_DB_FELT_BESK006.pdf
SELECT
    DTTOTAL.KOMKOD AS Kommunenummer,
    RIGHT('0' + CAST(DTTOTAL.PNR AS VARCHAR(10)), 10) AS CPR,
    CASE 
			WHEN DTTOTAL.ADRNVN IS NULL THEN
				'(unavngivet)'
			WHEN CHARINDEX(',', DTTOTAL.ADRNVN) > 0 THEN 
                RTRIM(SUBSTRING(DTTOTAL.ADRNVN, CHARINDEX(',', DTTOTAL.ADRNVN) + 1, LEN(DTTOTAL.ADRNVN))) + ' ' + LEFT(DTTOTAL.ADRNVN, CHARINDEX(',', DTTOTAL.ADRNVN) - 1)
            ELSE 
                RTRIM(DTTOTAL.ADRNVN) 
    END AS Navn,
	CASE WHEN DTTOTAL.ABMRK = 1 THEN 1 ELSE 0 END AS Beskyttet,
	RTRIM(Udlandsadresse.UADR1) AS AdresseLinje1,
	RTRIM(Udlandsadresse.UADR2) AS AdresseLinje2,
	RTRIM(Udlandsadresse.UADR3) AS AdresseLinje3,
	RTRIM(Udlandsadresse.UADR4) AS AdresseLinje4,
	RTRIM(Udlandsadresse.UADR5) AS AdresseLinje5
FROM
	dbo.DTTOTAL 
	LEFT JOIN dbo.DTAKTVEJ ON DTTOTAL.VEJKOD = DTAKTVEJ.VEJKOD AND DTTOTAL.KOMKOD = DTAKTVEJ.KOMKOD
	LEFT JOIN (SELECT DTUDRIND.* FROM DTUDRIND INNER JOIN (SELECT PNR, MAX(AJFDTO) AS AJFDTO FROM dbo.DTUDRIND WHERE ANNKOR IS NULL AND UADR1 IS NOT NULL AND UADR2 IS NOT NULL GROUP BY PNR)  AS SidsteUdlandsadresse ON DTUDRIND.PNR = SidsteUdlandsadresse.PNR AND DTUDRIND.AJFDTO = SidsteUdlandsadresse.AJFDTO AND DTUDRIND.ANNKOR IS NULL) AS Udlandsadresse ON Udlandsadresse.PNR = DTTOTAL.PNR AND DTTOTAL.STATUS = 80 AND DTTOTAL.UDINDMRK = '1'	
WHERE
	DTTOTAL.STATUS = 80 AND UADR1 IS NOT NULL AND UADR2 IS NOT NULL
ORDER BY DTTOTAL.PNR
