-- 02.06.2010 - Traen A/S - JEM/MBR
-- This query returns person information from DPR database.
-- The query conforms to the DPR interface documented at http://assets1.csc.com/dpr/downloads/DPR_DB_FELT_BESK006.pdf
SELECT
    DTTOTAL.KOMKOD AS Kommunenummer,
    RIGHT('0' + CAST(DTTOTAL.PNR AS VARCHAR(10)), 10) AS CPR,
    CASE 
			WHEN DTTOTAL.ADRNVN IS NULL THEN
				'(unavngivet)'
			WHEN CHARINDEX(',', DTTOTAL.ADRNVN) > 0 THEN 
                RTRIM(SUBSTRING(DTTOTAL.ADRNVN, CHARINDEX(',', DTTOTAL.ADRNVN) + 1, LEN(DTTOTAL.ADRNVN))) + ' ' + LEFT(DTTOTAL.ADRNVN, CHARINDEX(',', DTTOTAL.ADRNVN) - 1)
            ELSE 
                RTRIM(DTTOTAL.ADRNVN) 
    END +
    CASE DTTOTAL.STATUS 
            WHEN 70 THEN ' (forsvundet)' 
            WHEN 80 THEN ' (udvandret)' 
            WHEN 90 THEN ' (død)' 
            ELSE '' 
    END 
	AS Navn,
	CASE WHEN Adresse.VEJADNVN IS NULL OR LEN(LTRIM(Adresse.VEJADNVN)) = 0 OR Adresse.VEJADNVN = 'Adresse ikke komplet' THEN NULL ELSE Adresse.VEJKOD END AS Vejkode,
	CASE WHEN DTTOTAL.ABMRK = 1 THEN 1 ELSE 0 END AS Beskyttet,
	Adresse.VEJADNVN AS Vejnavn,
	CASE WHEN Adresse.HUSNR IS NULL THEN 'EJ I DPR' ELSE CAST(CAST(SUBSTRING(Adresse.HUSNR,1,3) AS SMALLINT) AS VARCHAR(3)) + RTRIM(SUBSTRING(Adresse.HUSNR,4,1)) END AS Husnummer,
	RTRIM(LTRIM((REPLACE(' ' + Adresse.ETAGE,' 0','')))) AS Etage,
    RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(' ' + Adresse.SIDEDOER,' 000',''),' 00',''),' 0',''))) AS SideDoer,
	Adresse.POSTNR AS Postnummer, 
	DTPOSTNR.POSTTXT AS Postdistrikt
FROM
	dbo.DTTOTAL 
	LEFT JOIN dbo.DTAKTVEJ ON DTTOTAL.VEJKOD = DTAKTVEJ.VEJKOD AND DTTOTAL.KOMKOD = DTAKTVEJ.KOMKOD
	LEFT JOIN (SELECT DTPERSBO.* FROM dbo.DTPERSBO INNER JOIN (SELECT PNR, MAX(TILFDTO) AS TILFDTO FROM dbo.DTPERSBO WHERE ANNKOR IS NULL GROUP BY PNR)  AS SidsteAddresse ON DTPERSBO.PNR = SidsteAddresse.PNR AND  DTPERSBO.TILFDTO = SidsteAddresse.TILFDTO AND DTPERSBO.ANNKOR IS NULL) AS Adresse ON Adresse.PNR = DTTOTAL.PNR
	LEFT JOIN dbo.DTPOSTNR ON DTPOSTNR.POSTNR = Adresse.POSTNR
	LEFT JOIN (SELECT DTUDRIND.* FROM DTUDRIND INNER JOIN (SELECT PNR, MAX(AJFDTO) AS AJFDTO FROM dbo.DTUDRIND WHERE ANNKOR IS NULL AND UADR1 IS NOT NULL AND UADR2 IS NOT NULL GROUP BY PNR)  AS SidsteUdlandsadresse ON DTUDRIND.PNR = SidsteUdlandsadresse.PNR AND DTUDRIND.AJFDTO = SidsteUdlandsadresse.AJFDTO AND DTUDRIND.ANNKOR IS NULL) AS Udlandsadresse ON Udlandsadresse.PNR = DTTOTAL.PNR AND DTTOTAL.STATUS = 80 AND DTTOTAL.UDINDMRK = '1'	
WHERE
	(DTTOTAL.STATUS < 10 OR DTTOTAL.STATUS IN (70, 80, 90)) AND  -- Kun aktive, forsvundne, udvandrede og døde personer
	(DTTOTAL.STATUS <> 80 OR Udlandsadresse.UADR1 IS NULL OR Udlandsadresse.UADR2 IS NULL)       -- Frasorter udlandsborgere vis de har en udlandsadresse
ORDER BY DTTOTAL.PNR
