//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CprBroker.Schemas.Part {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegModer", Namespace="urn:oio:sagdok:person:1.0.0", IsNullable=false)]
    public partial class SoegRelationType {
        
        private SoegVirkningType soegVirkningField;
        
        private UnikIdType referenceIDField;
        
        private string commentTextField;
        
        /// <remarks/>
        public SoegVirkningType SoegVirkning {
            get {
                return this.soegVirkningField;
            }
            set {
                this.soegVirkningField = value;
            }
        }
        
        /// <remarks/>
        public UnikIdType ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/vejsektoren.dk/core/schemas/xml/2007/03/31/")]
        public string CommentText {
            get {
                return this.commentTextField;
            }
            set {
                this.commentTextField = value;
            }
        }
    }
}