//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CprBroker.Schemas.Part {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/")]
    [System.Xml.Serialization.XmlRootAttribute("AddressComplete", Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/", IsNullable=false)]
    public partial class AddressCompleteType {
        
        private AddressAccessType addressAccessField;
        
        private AddressPostalType addressPostalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/")]
        public AddressAccessType AddressAccess {
            get {
                return this.addressAccessField;
            }
            set {
                this.addressAccessField = value;
            }
        }
        
        /// <remarks/>
        public AddressPostalType AddressPostal {
            get {
                return this.addressPostalField;
            }
            set {
                this.addressPostalField = value;
            }
        }
    }
}