// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 2.8.2.21705
//    <NameSpace>CprBroker.Schemas</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>True</DisableDebug><CustomUsings></CustomUsings>
//  <auto-generated>
// ------------------------------------------------------------------------------
namespace CprBroker.Schemas
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2009/07/01/")]
    [System.Xml.Serialization.XmlRootAttribute("Application", Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2009/07/01/", IsNullable = false)]
    public partial class ApplicationType
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string applicationIdField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string tokenField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime registrationDateField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool isApprovedField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime approvedDateField;

        public string ApplicationId
        {
            get
            {
                return this.applicationIdField;
            }
            set
            {
                this.applicationIdField = value;
            }
        }

        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public bool IsApproved
        {
            get
            {
                return this.isApprovedField;
            }
            set
            {
                this.isApprovedField = value;
            }
        }

        public System.DateTime ApprovedDate
        {
            get
            {
                return this.approvedDateField;
            }
            set
            {
                this.approvedDateField = value;
            }
        }
    }
}
