// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 2.8.2.21705
//    <NameSpace>CprBroker.Schemas</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings>
//  <auto-generated>
// ------------------------------------------------------------------------------
namespace CprBroker.Schemas
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/01/17/")]
    [System.Xml.Serialization.XmlRootAttribute("PersonCivilRegistrationStatusStructure", Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/01/17/", IsNullable = false)]
    public partial class PersonCivilRegistrationStatusStructureType
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private PersonCivilRegistrationStatusCodeType personCivilRegistrationStatusCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime personCivilRegistrationStatusStartDateField;

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
        public PersonCivilRegistrationStatusCodeType PersonCivilRegistrationStatusCode
        {
            get
            {
                return this.personCivilRegistrationStatusCodeField;
            }
            set
            {
                this.personCivilRegistrationStatusCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime PersonCivilRegistrationStatusStartDate
        {
            get
            {
                return this.personCivilRegistrationStatusStartDateField;
            }
            set
            {
                this.personCivilRegistrationStatusStartDateField = value;
            }
        }
    }
}
