// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 2.8.2.21705
//    <NameSpace>CprBroker.Schemas</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings>
//  <auto-generated>
// ------------------------------------------------------------------------------
namespace CprBroker.Schemas
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/")]
    [System.Xml.Serialization.XmlRootAttribute("PersonNameStructure", Namespace = "http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/", IsNullable = false)]
    public partial class PersonNameStructureType
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string personGivenNameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string personMiddleNameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string personSurnameNameField;

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string PersonGivenName
        {
            get
            {
                return this.personGivenNameField;
            }
            set
            {
                this.personGivenNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string PersonMiddleName
        {
            get
            {
                return this.personMiddleNameField;
            }
            set
            {
                this.personMiddleNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string PersonSurnameName
        {
            get
            {
                return this.personSurnameNameField;
            }
            set
            {
                this.personSurnameNameField = value;
            }
        }
    }
}
