// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 2.8.2.1
//    <NameSpace>CPRBroker.Schemas</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>True</DisableDebug><CustomUsings></CustomUsings>
//  <auto-generated>
// ------------------------------------------------------------------------------
namespace CPRBroker.Schemas
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2009/07/01/")]
    [System.Xml.Serialization.XmlRootAttribute("PersonNameAndAddressStructure", Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2009/07/01/", IsNullable = false)]
    public partial class PersonNameAndAddressStructureType
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private SimpleCPRPersonType simpleCPRPersonField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private AddressIdentifierCodeType addressIdentifierCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool addressIdentifierCodeFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private object itemField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool personInformationProtectionIndicatorField;

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/01/17/")]
        public SimpleCPRPersonType SimpleCPRPerson
        {
            get
            {
                return this.simpleCPRPersonField;
            }
            set
            {
                this.simpleCPRPersonField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
        public AddressIdentifierCodeType AddressIdentifierCode
        {
            get
            {
                return this.addressIdentifierCodeField;
            }
            set
            {
                this.addressIdentifierCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressIdentifierCodeSpecified
        {
            get
            {
                return this.addressIdentifierCodeFieldSpecified;
            }
            set
            {
                this.addressIdentifierCodeFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DanishAddressStructure", typeof(DanishAddressStructureType), Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
        [System.Xml.Serialization.XmlElementAttribute("ForeignAddressStructure", typeof(ForeignAddressStructureType), Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
        public bool PersonInformationProtectionIndicator
        {
            get
            {
                return this.personInformationProtectionIndicatorField;
            }
            set
            {
                this.personInformationProtectionIndicatorField = value;
            }
        }
    }
}
