<?xml version="1.0" encoding="utf-8"?>
<Database Name="CPRBroker" Class="CPRBrokerDALDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.RelationshipType" Member="RelationshipTypes">
    <Type Name="RelationshipType">
      <Column Name="RelationshipTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ForwardName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BackwardName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RelationshipType_Relationship" Member="Relationships" ThisKey="RelationshipTypeId" OtherKey="RelationshipTypeId" Type="Relationship" />
    </Type>
  </Table>
  <Table Name="dbo.MaritalStatusType" Member="MaritalStatusTypes">
    <Type Name="MaritalStatusType">
      <Column Name="MaritalStatusTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaritalStatusName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MaritalStatusType_Person" Member="Persons" ThisKey="MaritalStatusTypeId" OtherKey="MaritalStatusTypeId" Type="Person" />
      <Association Name="MaritalStatusType_MaritalRelationship" Member="MaritalRelationships" ThisKey="MaritalStatusTypeId" OtherKey="MaritalStatusId" Type="MaritalRelationship" />
    </Type>
  </Table>
  <Table Name="dbo.LogType" Member="LogTypes">
    <Type Name="LogType">
      <Column Name="LogTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LogType_LogEntry" Member="LogEntries" ThisKey="LogTypeId" OtherKey="LogTypeId" Type="LogEntry" />
    </Type>
  </Table>
  <Table Name="dbo.Gender" Member="Genders">
    <Type Name="Gender">
      <Column Name="GenderId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GenderName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Gender_Person" Member="Persons" ThisKey="GenderId" OtherKey="GenderId" Type="Person" />
    </Type>
  </Table>
  <Table Name="dbo.AddressType" Member="AddressTypes">
    <Type Name="AddressType">
      <Column Name="AddressTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddressTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AddressStatus" Member="AddressStatus">
    <Type Name="AddressStatus">
      <Column Name="AddressStatusId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddressStatusName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="AddressStatus_Address" Member="Addresses" ThisKey="AddressStatusId" OtherKey="AddressStatusId" Type="Address" />
    </Type>
  </Table>
  <Table Name="dbo.DataProviderType" Member="DataProviderTypes">
    <Type Name="DataProviderType">
      <Column Name="DataProviderTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsExternal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DataProviderType_DataProvider" Member="DataProviders" ThisKey="DataProviderTypeId" OtherKey="DataProviderTypeId" Type="DataProvider" />
    </Type>
  </Table>
  <Table Name="dbo.Application" Member="Applications">
    <Type Name="Application">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Application_LogEntry" Member="LogEntries" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="LogEntry" />
    </Type>
  </Table>
  <Table Name="dbo.DataProvider" Member="DataProviders">
    <Type Name="DataProvider">
      <Column Name="DataProviderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataProviderTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConnectionString" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DataProviderType_DataProvider" Member="DataProviderType" ThisKey="DataProviderTypeId" OtherKey="DataProviderTypeId" Type="DataProviderType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetailLevel" Member="DetailLevels">
    <Type Name="DetailLevel">
      <Column Name="DetailLevelId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DetailLevel_Person" Member="Persons" ThisKey="DetailLevelId" OtherKey="DetailLevelId" Type="Person" />
    </Type>
  </Table>
  <Table Name="dbo.ChildRelationship" Member="ChildRelationships">
    <Type Name="ChildRelationship">
      <Column Name="RelationshipId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Relationship_ChildRelationship" Member="Relationship" ThisKey="RelationshipId" OtherKey="RelationshipId" Type="Relationship" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogEntry" Member="LogEntries">
    <Type Name="LogEntry">
      <Column Name="LogEntryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LogTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserToken" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MethodName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DataObjectType" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DataObjectXml" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Application_LogEntry" Member="Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="Application" IsForeignKey="true" />
      <Association Name="LogType_LogEntry" Member="LogType" ThisKey="LogTypeId" OtherKey="LogTypeId" Type="LogType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Municipality" Member="Municipalities">
    <Type Name="Municipality">
      <Column Name="MunicipalityCode" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MunicipalityName" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Association Name="Municipality_Address" Member="Addresses" ThisKey="MunicipalityCode" OtherKey="MunicipalityCode" Type="Address" />
    </Type>
  </Table>
  <Table Name="dbo.CustodyRelationship" Member="CustodyRelationships">
    <Type Name="CustodyRelationship">
      <Column Name="RelationshipId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TimedRelationship_CustodyRelationship" Member="TimedRelationship" ThisKey="RelationshipId" OtherKey="RelationshipId" Type="TimedRelationship" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="PersonId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DetailLevelId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NationalityCountryAlpha2Code" Storage="_NationalityCountryCode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PersonNumber" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="NameForAddressing" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BirthDateUncertaintyIndicator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeathDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeathDateUncertaintyIndicator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaritalStatusTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonStatusTypeCode" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="PersonStatusDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GenderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonProtectionIndicator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PersonProtectionIndicatorStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PersonProtectionIndicatorEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsTestPerson" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Person_Relationship" Member="Relationships" ThisKey="PersonId" OtherKey="PersonId" Type="Relationship" />
      <Association Name="Person_Relationship1" Member="Relationships1" ThisKey="PersonId" OtherKey="RelatedPersonId" Type="Relationship" />
      <Association Name="Person_Address" Member="Address" ThisKey="PersonId" OtherKey="PersonId" Type="Address" Cardinality="One" />
      <Association Name="DetailLevel_Person" Member="DetailLevel" ThisKey="DetailLevelId" OtherKey="DetailLevelId" Type="DetailLevel" IsForeignKey="true" />
      <Association Name="Gender_Person" Member="Gender" ThisKey="GenderId" OtherKey="GenderId" Type="Gender" IsForeignKey="true" />
      <Association Name="MaritalStatusType_Person" Member="MaritalStatusType" ThisKey="MaritalStatusTypeId" OtherKey="MaritalStatusTypeId" Type="MaritalStatusType" IsForeignKey="true" />
      <Association Name="PersonStatusType_Person" Member="PersonStatusType" ThisKey="PersonStatusTypeCode" OtherKey="PersonStatusTypeCode" Type="PersonStatusType" IsForeignKey="true" />
      <Association Name="Country_Person" Member="Country" ThisKey="NationalityCountryAlpha2Code" OtherKey="Alpha2Code" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonStatusType" Member="PersonStatusTypes">
    <Type Name="PersonStatusType">
      <Column Name="PersonStatusTypeCode" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersonStatusName" Type="System.String" DbType="NVarChar(90) NOT NULL" CanBeNull="false" />
      <Association Name="PersonStatusType_Person" Member="Persons" ThisKey="PersonStatusTypeCode" OtherKey="PersonStatusTypeCode" Type="Person" />
    </Type>
  </Table>
  <Table Name="dbo.TimedRelationship" Member="TimedRelationships">
    <Type Name="TimedRelationship">
      <Column Name="RelationshipId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TimedRelationship_CustodyRelationship" Member="CustodyRelationship" ThisKey="RelationshipId" OtherKey="RelationshipId" Type="CustodyRelationship" Cardinality="One" />
      <Association Name="TimedRelationship_MaritalRelationship" Member="MaritalRelationship" Storage="_MaritalRelationship1" ThisKey="RelationshipId" OtherKey="RelationshipId" Type="MaritalRelationship" Cardinality="One" />
      <Association Name="Relationship_TimedRelationship" Member="Relationship" ThisKey="RelationshipId" OtherKey="RelationshipId" Type="Relationship" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Relationship" Member="Relationships">
    <Type Name="Relationship">
      <Column Name="RelationshipId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RelatedPersonId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RelationshipTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Relationship_ChildRelationship" Member="ChildRelationship" ThisKey="RelationshipId" OtherKey="RelationshipId" Type="ChildRelationship" Cardinality="One" />
      <Association Name="Relationship_TimedRelationship" Member="TimedRelationship" ThisKey="RelationshipId" OtherKey="RelationshipId" Type="TimedRelationship" Cardinality="One" />
      <Association Name="Person_Relationship" Member="Person" ThisKey="PersonId" OtherKey="PersonId" Type="Person" IsForeignKey="true" />
      <Association Name="Person_Relationship1" Member="RelatedPerson" ThisKey="RelatedPersonId" OtherKey="PersonId" Type="Person" IsForeignKey="true" />
      <Association Name="RelationshipType_Relationship" Member="RelationshipType" ThisKey="RelationshipTypeId" OtherKey="RelationshipTypeId" Type="RelationshipType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MaritalRelationship" Member="MaritalRelationships">
    <Type Name="MaritalRelationship">
      <Column Name="RelationshipId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaritalStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TimedRelationship_MaritalRelationship" Member="TimedRelationship" Storage="_TimedRelationship1" ThisKey="RelationshipId" OtherKey="RelationshipId" Type="TimedRelationship" IsForeignKey="true" />
      <Association Name="MaritalStatusType_MaritalRelationship" Member="MaritalStatusType" ThisKey="MaritalStatusId" OtherKey="MaritalStatusTypeId" Type="MaritalStatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="PersonId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddressStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryAlpha2Code" Storage="_CountryCode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="MunicipalityCode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="StreetCode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="StreetName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StreetNameForAddressing" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StreetBuildingIdentifier" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="FloorIdentifier" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="SuiteIdentifier" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="MailDeliverSubLocationIdentifier" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="DistrictSubDivisionIdentifier" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="PostBoxIdentifier" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PostDistrictName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CareOfName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line4" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line5" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line6" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LocationDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="AddressStatus_Address" Member="AddressStatus" ThisKey="AddressStatusId" OtherKey="AddressStatusId" Type="AddressStatus" IsForeignKey="true" />
      <Association Name="Municipality_Address" Member="Municipality" ThisKey="MunicipalityCode" OtherKey="MunicipalityCode" Type="Municipality" IsForeignKey="true" />
      <Association Name="Person_Address" Member="Person" ThisKey="PersonId" OtherKey="PersonId" Type="Person" IsForeignKey="true" />
      <Association Name="Country_Address" Member="Country" ThisKey="CountryAlpha2Code" OtherKey="Alpha2Code" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OperationType" Member="OperationTypes">
    <Type Name="OperationType">
      <Column Name="OperationTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OperationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SourceTableName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OldTableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="Alpha2Code" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Alpha3Code" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NumericCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanishCountryName" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="DanishCountryName2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KmdCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KmdCode2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KmdCode3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Country_Person" Member="Persons" ThisKey="Alpha2Code" OtherKey="NationalityCountryAlpha2Code" Type="Person" />
      <Association Name="Country_Address" Member="Addresses" ThisKey="Alpha2Code" OtherKey="CountryAlpha2Code" Type="Address" />
    </Type>
  </Table>
</Database>