//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CprBroker.Providers.CprServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CprBroker.Providers.CprServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Gctp v=&quot;1.0&quot; &gt;
        ///    &lt;System r=&quot;CprSoeg&quot;&gt;
        ///        &lt;Service r=&quot;ADRESSE3&quot;&gt;
        ///            &lt;CprServiceHeader r=&quot;ADRESSE3&quot;&gt;
        ///                &lt;Key&gt;
        ///                    &lt;Field r=&quot;PNR&quot; v=&quot;&quot;/&gt;
        ///                    &lt;Field r=&quot;AKX&quot; v=&quot;X&quot;/&gt;
        ///                &lt;/Key&gt;
        ///            &lt;/CprServiceHeader&gt;
        ///        &lt;/Service&gt;
        ///    &lt;/System&gt;
        ///&lt;/Gctp&gt;.
        /// </summary>
        public static string ADRESSE3 {
            get {
                return ResourceManager.GetString("ADRESSE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gctp v=&quot;1.0&quot; &gt;
        ///    &lt;System r=&quot;CprSoeg&quot;&gt;
        ///        &lt;Service r=&quot;ADRSOG1&quot;&gt;
        ///            &lt;CprServiceHeader r=&quot;ADRSOG1&quot;&gt;
        ///                &lt;Key&gt;
        ///                    &lt;Field r=&quot;NVN&quot; v=&quot;&quot;/&gt;
        ///                    &lt;Field r=&quot;NVN1&quot; v=&quot;&quot;/&gt;
        ///                    &lt;Field r=&quot;NVN2&quot; v=&quot;&quot;/&gt;
        ///                    &lt;Field r=&quot;NVN3&quot; v=&quot;&quot;/&gt;
        ///
        ///                    &lt;Field r=&quot;KON&quot; v=&quot;&quot;/&gt;
        ///
        ///
        ///                    &lt;Field r=&quot;VEJK&quot; v=&quot;&quot; required=&quot;true&quot; requiredGroup=&quot;vej&quot;/&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ADRSOG1 {
            get {
                return ResourceManager.GetString("ADRSOG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;root xmlns=&quot;http://www.cpr.dk&quot;&gt;
        ///    &lt;Gctp v=&quot;1.0&quot;&gt;
        ///        &lt;Sik function=&quot;newpass&quot; userid=&quot;&quot; password=&quot;&quot; newpass1=&quot;&quot; /&gt;
        ///    &lt;/Gctp&gt;
        ///&lt;/root&gt;.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gctp v=&quot;1.0&quot; &gt;
        ///    &lt;System r=&quot;CprSoeg&quot;&gt;
        ///        &lt;Service r=&quot;NVNSOG2&quot;&gt;
        ///            &lt;CprServiceHeader r=&quot;NVNSOG2&quot;&gt;
        ///                &lt;Key&gt;
        ///                    &lt;!--Show how many people match the criteria--&gt;
        ///                    &lt;Field r=&quot;AIA&quot; v=&quot;&quot;/&gt;
        ///
        ///                    &lt;!--Age from--&gt;
        ///                    &lt;Field r=&quot;ALDF&quot; v=&quot;&quot;/&gt;
        ///
        ///                    &lt;!--Age to--&gt;
        ///                    &lt;Field r=&quot;ALDT&quot; v=&quot;&quot;/&gt;
        ///
        ///                    &lt;!--Search h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NVNSOG2 {
            get {
                return ResourceManager.GetString("NVNSOG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;root xmlns=&quot;http://www.cpr.dk&quot;&gt;
        ///    &lt;Gctp v=&quot;1.0&quot;&gt;
        ///        &lt;Sik function= &quot;signon&quot; userid=&quot;&quot; password=&quot;&quot;/&gt;
        ///    &lt;/Gctp&gt;
        ///&lt;/root&gt;.
        /// </summary>
        public static string OrdinaryLogon {
            get {
                return ResourceManager.GetString("OrdinaryLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gctp v=&quot;1.0&quot; &gt;
        ///    &lt;System r=&quot;CprSoeg&quot;&gt;
        ///        &lt;Service r=&quot;[MethodName]&quot;&gt;
        ///            &lt;CprServiceHeader r=&quot;[MethodName]&quot;&gt;
        ///                &lt;Key&gt;
        ///                &lt;/Key&gt;
        ///            &lt;/CprServiceHeader&gt;
        ///        &lt;/Service&gt;
        ///    &lt;/System&gt;
        ///&lt;/Gctp&gt;.
        /// </summary>
        public static string SearchTemplate {
            get {
                return ResourceManager.GetString("SearchTemplate", resourceCulture);
            }
        }
    }
}
