<?xml version="1.0" encoding="utf-8"?>
<Database Name="PART" Class="DataProvidersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.DataProviderType" Member="DataProviderTypes">
    <Type Name="DataProviderType">
      <Column Name="DataProviderTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsExternal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DataProviderType_DataProvider" Member="DataProviders" ThisKey="DataProviderTypeId" OtherKey="DataProviderTypeId" Type="DataProvider" />
    </Type>
  </Table>
  <Table Name="dbo.DataProvider" Member="DataProviders">
    <Type Name="DataProvider">
      <Column Name="DataProviderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataProviderTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConnectionString" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DataProvider_DataProviderProperty" Member="DataProviderProperties" ThisKey="DataProviderId" OtherKey="DataProviderId" Type="DataProviderProperty" />
      <Association Name="DataProviderType_DataProvider" Member="DataProviderType" ThisKey="DataProviderTypeId" OtherKey="DataProviderTypeId" Type="DataProviderType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataProviderProperty" Member="DataProviderProperties">
    <Type Name="DataProviderProperty">
      <Column Name="DataProviderPropertyId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataProviderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="DataProvider_DataProviderProperty" Member="DataProvider" ThisKey="DataProviderId" OtherKey="DataProviderId" Type="DataProvider" IsForeignKey="true" />
    </Type>
  </Table>
</Database>