<?xml version="1.0" encoding="utf-8"?><Database Name="E_M" Class="E_MDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.JY64000V" Member="Citizens">
    <Type Name="Citizen">
      <Column Name="PERSONNUMMER" Member="PNR" Type="System.Decimal" DbType="Decimal(11,0)" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KOMMUNENUMMER" Member="MunicipalityCode" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Column Name="FODSEL_DATO" Member="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="PERSONNR_OPRETDATO" Member="PNRCreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="PERSONNR_MRK_DATO" Member="PNRMarkingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="KON" Member="Gender" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="STILLING" Member="Occupation" Type="System.String" DbType="Char(34)" CanBeNull="false" />
      <Column Name="STILLING_DATO" Member="OccupationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="ADRESSERINGSNAVN" Member="AddressingName" Type="System.String" DbType="Char(34)" CanBeNull="false" />
      <Column Name="ADRNAVN_DATO" Member="AddressingNameDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="FOLKEKIRKE_MYND_KD" Member="ChurchAuthorityCode" Storage="_NationalChurchAuthorityCode" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Column Name="FOLKEKIRK_TILH_MRK" Member="ChurchMarker" Storage="_NationalChurchMarker" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="FOLKEKIRK_MRK_DATO" Member="ChurchMarkerDate" Storage="_NationalChurchMarkerDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="BORGERSTATUS_KODE" Member="CitizenStatusCode" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Column Name="BORGERSTATUS_TS" Member="CitizenStatusTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="FODSELSREG_MYND_KD" Member="BirthRegistrationAuthorityCode" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Column Name="FODSELSREG_DATO" Member="BirthRegistrationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="FODESTED_TEKST" Member="BirthPlaceText" Storage="_BirthRegistrationText" Type="System.String" DbType="Char(20)" CanBeNull="false" />
      <Column Name="ANTAL_BORN" Member="NumberOfChildren" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Column Name="CPR_FOLKEKIRKE_TS" Member="CprChurchTimestamp" Storage="_CpcNationalChurchTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="CPR_PERSON_TS" Member="CprPersonTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="ADR_TILFLYT_TS" Member="AddtessStartTS" Storage="_ArrivalTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="VEJ_KODE" Member="RoadCode" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Column Name="HUS_NUMMER" Member="HouseNumber" Type="System.String" DbType="Char(4)" CanBeNull="false" />
      <Column Name="ETAGE" Member="Floor" Type="System.String" DbType="Char(2)" CanBeNull="false" />
      <Column Name="SIDE_DORNR" Member="Door" Type="System.String" DbType="Char(4)" CanBeNull="false" />
      <Column Name="BYGNING_NUMMER" Member="BuildingNumber" Type="System.String" DbType="Char(4)" CanBeNull="false" />
      <Column Name="ADR_FRAFLYT_TS" Member="AddressEndTS" Storage="_DepartureTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="CO_NAVN" Member="CareOfName" Type="System.String" DbType="Char(34)" CanBeNull="false" />
      <Column Name="VEJSIDE_F_LIG_ULIG" Member="OddEvenRoadSide" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="KOM_TILFLYTDATO" Member="MunicipalityArrivalDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="FRAFLYT_KOMMUNENR" Member="DepartureMunicipalityCode" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Column Name="ADRESSEBESKYT_DATO" Member="AddressProtectionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="ADR_BESKYT_SLTDATO" Member="AddressProtectionEndDate" Storage="_AddressProtectionRemovalDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="VEJVIS_BESKYT_DATO" Member="DirectoryProtectionDate" Storage="_DiretoryProtectionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="CIVILSTAND_TS" Member="MaritalStatusTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="CIVILSTAND" Member="MaritalStatus" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="CIVILST_OPHOR_TS" Member="MaritalStatusTerminationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="PERSONNR_AGTEFALLE" Member="SpousePNR" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="false" />
      <Column Name="AGTEFALLE_FLAG" Member="SpouseFlag" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="LAND_KODE" Member="CountryCode" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Column Name="STATSB_RET_TS" Member="NationalityChangeTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="STATBORG_OPHOR_TS" Member="NationalityTerminationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="PERSONNUMMER_MOR" Member="MotherPNR" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="false" />
      <Column Name="PERSONNUMMER_FAR" Member="FatherPNR" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="false" />
      <Column Name="MOR_DOK" Member="MotherDocument" Type="System.String" DbType="Char(3)" CanBeNull="false" />
      <Column Name="FAR_DOK" Member="FatherDocument" Type="System.String" DbType="Char(3)" CanBeNull="false" />
      <Column Name="VEJVIS_BESK_SLTDTO" Member="DirectoryProtectionEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="FODSEL_UM" Member="BirthdateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="PERSONNR_OPRET_UM" Member="PNRCreationdateUncertainty" Storage="_PnrCreationdateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="PERSONNR_MRK_UM" Member="PNRMarkingDateUncertainty" Storage="_PnrMarkingDateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="STILLING_UM" Member="OccupationDateUncertainty" Storage="_PostDateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="ADRNAVN_UM" Member="AddressingNameDateUncertainty" Storage="_AddressingNameUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="FOLKEKIRK_MRK_UM" Member="ChurchMarkerDateUncertainty" Storage="_NationalChurchMarkerUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="BORGERSTATUS_UM" Member="CitizenStatusTimestampUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="FODSELSREG_UM" Member="BirthRegistrationDateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="ADR_TILFLYT_UM" Member="RelocationTimestampUncertainty" Storage="_ArrivalTimestampUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="ADR_FRAFLYT_UM" Member="DepartureTimestampUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="KOM_TILFLYT_UM" Member="MunicipalityArrivalDateUncertainty" Storage="_MunicipalityArrivalTimestampUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="ADR_BESKYT_UM" Member="AddressProtectionDateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="ADR_BESKYT_SLT_UM" Member="AddressProtectionEndDateUncertainty" Storage="_AddressProtectionTerminationDateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="VEJVIS_BESKYT_UM" Member="DirectoryProtectionDateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="CIVILSTAND_UM" Member="MaritalStatusTimestampUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="CIVILST_OPHOR_UM" Member="MaritalStatusTerminationTimestampUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="STATSB_RET_UM" Member="NationalityChangeTimestampUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="STATBORG_OPHOR_UM" Member="NationalityTerminationTimestampUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Column Name="VEJVIS_BESK_SLT_UM" Member="DirectoryProtectionEndDateUncertainty" Storage="_DirectoryProtectionRemovalDateUncertainty" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Association Name="Citizen_Child" Member="ChildrenAsMother" ThisKey="PNR" OtherKey="MotherPNR" Type="Child" />
      <Association Name="Citizen_Child1" Member="ChildrenAsFather" ThisKey="PNR" OtherKey="FatherPNR" Type="Child" />
      <Association Name="Citizen_CitizenReadyAddress" Member="CitizenReadyAddress" ThisKey="PNR" OtherKey="PNR" Type="CitizenReadyAddress" Cardinality="One" />
      <Association Name="Authority_Citizen" Member="BirthRegistrationAuthority" ThisKey="BirthRegistrationAuthorityCode" OtherKey="AuthorityCode" Type="Authority" IsForeignKey="true" />
      <Association Name="Citizen_Citizen" Member="Spouse" ThisKey="SpousePNR" OtherKey="PNR" Type="Citizen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JY64200V" Member="Childs">
    <Type Name="Child">
      <Column Name="PERSONNUMMER" Member="PNR" Type="System.Decimal" DbType="Decimal(11,0)" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PERSONNUMMER_MOR" Member="MotherPNR" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="false" />
      <Column Name="PERSONNUMMER_FAR" Member="FatherPNR" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="false" />
      <Column Name="MOR_DOK" Member="MotherDocument" Type="System.String" DbType="Char(3)" CanBeNull="false" />
      <Column Name="FAR_DOK" Member="FatherDocument" Type="System.String" DbType="Char(3)" CanBeNull="false" />
      <Column Name="BORGERSTATUS_KODE" Member="CitizenStatusCode" Type="System.Int16" DbType="SmallInt" CanBeNull="false" />
      <Association Name="Citizen_Child" Member="Mother" ThisKey="MotherPNR" OtherKey="PNR" Type="Citizen" IsForeignKey="true" />
      <Association Name="Citizen_Child1" Member="Father" ThisKey="FatherPNR" OtherKey="PNR" Type="Citizen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AA74000V" Member="Authorities">
    <Type Name="Authority">
      <Column Name="MYNDIGHED_KODE" Member="AuthorityCode" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MYNDIGHED_TYPE" Member="AuthorityType" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MYNDIGHED_NAVN" Member="AuthorityName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="MYNDIGHED_ADRESSAT" Type="System.String" DbType="Char(34) NOT NULL" CanBeNull="false" />
      <Column Name="MYNDIGHED_ADR_1" Type="System.String" DbType="Char(34) NOT NULL" CanBeNull="false" />
      <Column Name="MYNDIGHED_ADR_2" Type="System.String" DbType="Char(34) NOT NULL" CanBeNull="false" />
      <Column Name="MYNDIGHED_ADR_3" Type="System.String" DbType="Char(34) NOT NULL" CanBeNull="false" />
      <Column Name="MYNDIGHED_ADR_4" Type="System.String" DbType="Char(34) NOT NULL" CanBeNull="false" />
      <Column Name="MYNDIGHED_TLFNR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MYND_OPRETDATO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MYND_OPHORDATO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CPR_MYNDIGHED_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CPR_MYND_TYPE_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FAXNR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MYND_OPRET_UM" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="MYND_OPHOR_UM" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="Authority_Citizen" Member="Citizens" ThisKey="AuthorityCode" OtherKey="BirthRegistrationAuthorityCode" Type="Citizen" />
    </Type>
  </Table>
  <Table Name="dbo.AA73000V" Member="Roads">
    <Type Name="Road">
      <Column Name="KOMMUNENUMMER" Member="MunicipalityCode" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VEJ_KODE" Member="RoadCode" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VEJ_NAVN" Member="RoadName" Type="System.String" DbType="Char(40) NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_ADRESSENAVN" Member="RoadAddressingName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_OPRET_TS" Member="RoadCreationDate" Storage="_VEJ_OPRET_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_OPHOR_TS" Member="RoadEndDate" Storage="_VEJ_OPHOR_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_KORR_MRK" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="HENV_AKTUEL_KOM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="HENV_AKTUEL_VEJ" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_TIL_KOMMUNE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_TIL_VEJ" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_FRA_KOMMUNE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_FRA_VEJ" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CPR_VEJ_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_OPRET_UM" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_OPHOR_UM" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_NAVN_SOGE" Member="RoadSearchName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_NAVN_FONETIK" Member="RoadPhoneticName" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Association Name="CitizenReadyAddress_Road" Member="CitizenReadyAddress" ThisKey="MunicipalityCode,RoadCode" OtherKey="MunicipalityCode,RoadCode" Type="CitizenReadyAddress" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JY67800V" Member="CitizenReadyAddresses">
    <Type Name="CitizenReadyAddress">
      <Column Name="EKOMNR" Member="MunicipalityCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PERSONNUMMER" Member="PNR" Type="System.Decimal" DbType="Decimal(11,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ADRESSERINGSNAVN" Member="AddressingName" Type="System.String" DbType="Char(34) NOT NULL" CanBeNull="false" />
      <Column Name="CO_NAVN" Member="CareOfName" Type="System.String" DbType="Char(34) NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_KODE" Member="RoadCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="VEJ_NAVN" Member="RoadName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="HUS_NUMMER" Member="HouseNumber" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="ETAGE" Member="Floor" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="SIDE_DORNR" Member="Door" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="BYNAVN" Member="CityName" Type="System.String" DbType="Char(34) NOT NULL" CanBeNull="false" />
      <Column Name="POSTNR" Member="PostCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="POSTDISTRIKT" Member="PostDistrict" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Association Name="CitizenReadyAddress_Road" Member="Roads" ThisKey="MunicipalityCode,RoadCode" OtherKey="MunicipalityCode,RoadCode" Type="Road" />
      <Association Name="Citizen_CitizenReadyAddress" Member="Citizen" ThisKey="PNR" OtherKey="PNR" Type="Citizen" IsForeignKey="true" />
    </Type>
  </Table>
</Database>