//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CPRBroker.Providers.KMD.WS_AN08100 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:zsrxsd.kmd.dk:AN08100")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08100", IsNullable=false)]
    public partial class AN08100 {
        
        private SOEGEDATA inputRecordField;
        
        /// <remarks/>
        public SOEGEDATA InputRecord {
            get {
                return this.inputRecordField;
            }
            set {
                this.inputRecordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08100")]
    public partial class SOEGEDATA {
        
        private string dAGFRAField;
        
        private string dAGTILField;
        
        private string mAANEDFRAField;
        
        private string mAANEDTILField;
        
        private string aARFRAField;
        
        private string aARTILField;
        
        private string aARHUNDFRAField;
        
        private string aARHUNDTILField;
        
        private string sTATUSField;
        
        private string kOENField;
        
        /// <remarks/>
        public string DAGFRA {
            get {
                return this.dAGFRAField;
            }
            set {
                this.dAGFRAField = value;
            }
        }
        
        /// <remarks/>
        public string DAGTIL {
            get {
                return this.dAGTILField;
            }
            set {
                this.dAGTILField = value;
            }
        }
        
        /// <remarks/>
        public string MAANEDFRA {
            get {
                return this.mAANEDFRAField;
            }
            set {
                this.mAANEDFRAField = value;
            }
        }
        
        /// <remarks/>
        public string MAANEDTIL {
            get {
                return this.mAANEDTILField;
            }
            set {
                this.mAANEDTILField = value;
            }
        }
        
        /// <remarks/>
        public string AARFRA {
            get {
                return this.aARFRAField;
            }
            set {
                this.aARFRAField = value;
            }
        }
        
        /// <remarks/>
        public string AARTIL {
            get {
                return this.aARTILField;
            }
            set {
                this.aARTILField = value;
            }
        }
        
        /// <remarks/>
        public string AARHUNDFRA {
            get {
                return this.aARHUNDFRAField;
            }
            set {
                this.aARHUNDFRAField = value;
            }
        }
        
        /// <remarks/>
        public string AARHUNDTIL {
            get {
                return this.aARHUNDTILField;
            }
            set {
                this.aARHUNDTILField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string KOEN {
            get {
                return this.kOENField;
            }
            set {
                this.kOENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08100")]
    public partial class SVARPERSONER {
        
        private string pERSONNUMMERField;
        
        private string aDRESSERINGSNAVNField;
        
        private string aDRESSEField;
        
        private string bEMAERKNINGField;
        
        /// <remarks/>
        public string PERSONNUMMER {
            get {
                return this.pERSONNUMMERField;
            }
            set {
                this.pERSONNUMMERField = value;
            }
        }
        
        /// <remarks/>
        public string ADRESSERINGSNAVN {
            get {
                return this.aDRESSERINGSNAVNField;
            }
            set {
                this.aDRESSERINGSNAVNField = value;
            }
        }
        
        /// <remarks/>
        public string ADRESSE {
            get {
                return this.aDRESSEField;
            }
            set {
                this.aDRESSEField = value;
            }
        }
        
        /// <remarks/>
        public string BEMAERKNING {
            get {
                return this.bEMAERKNINGField;
            }
            set {
                this.bEMAERKNINGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08100")]
    public partial class SVAR {
        
        private short rETURKODEField;
        
        private string rETURTEKSTField;
        
        /// <remarks/>
        public short RETURKODE {
            get {
                return this.rETURKODEField;
            }
            set {
                this.rETURKODEField = value;
            }
        }
        
        /// <remarks/>
        public string RETURTEKST {
            get {
                return this.rETURTEKSTField;
            }
            set {
                this.rETURTEKSTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:zsrxsd.kmd.dk:AN08100")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:zsrxsd.kmd.dk:AN08100", IsNullable=false)]
    public partial class AN08100Response {
        
        private SVAR outputRecordField;
        
        private SVARPERSONER[] outputArrayRecordField;
        
        /// <remarks/>
        public SVAR OutputRecord {
            get {
                return this.outputRecordField;
            }
            set {
                this.outputRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OutputArrayRecord")]
        public SVARPERSONER[] OutputArrayRecord {
            get {
                return this.outputArrayRecordField;
            }
            set {
                this.outputArrayRecordField = value;
            }
        }
    }
}
