<?xml version="1.0" encoding="utf-8"?>
<Database Name="PART" Class="PartDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.PersonMapping" Member="PersonMappings">
    <Type Name="PersonMapping">
      <Column Name="UUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CprNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Gender" Member="Genders">
    <Type Name="Gender">
      <Column Name="GenderId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GenderName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Gender_PersonAttribute" Member="PersonAttributes" ThisKey="GenderId" OtherKey="GenderId" Type="PersonAttribute" />
    </Type>
  </Table>
  <Table Name="dbo.ForeignCitizenData" Member="ForeignCitizenDatas">
    <Type Name="ForeignCitizenData">
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ForeignNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PermissionNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NationalityCountryAlpha2Code" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Association Name="PersonAttribute_ForeignCitizenData" Member="PersonAttribute" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonAttribute" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnknownCitizenData" Member="UnknownCitizenDatas">
    <Type Name="UnknownCitizenData">
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReplacementCprNumber" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="PersonAttribute_UnknownCitizenData" Member="PersonAttribute" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonAttribute" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CprData" Member="CprDatas">
    <Type Name="CprData">
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddressingName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HasNameAndAddressProtection" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsBirthdateUncertain" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CprNumber" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="IndividualTrackStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NationalityCountryAlpha2Code" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Association Name="CprData_Address" Member="Address" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="Address" Cardinality="One" />
      <Association Name="PersonAttribute_CprData" Member="PersonAttribute" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonAttribute" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonStates" Member="PersonStates">
    <Type Name="PersonState">
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaritalStatusTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaritalStatusStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaritalStatusEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LifeStatusTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LifeStatusStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LifeStatusEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PersonRegistration_PersonState" Member="PersonRegistration" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddressStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryAlpha2Code" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="MunicipalityCode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="StreetCode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="StreetName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StreetNameForAddressing" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StreetBuildingIdentifier" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="FloorIdentifier" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="SuiteIdentifier" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="MailDeliverSubLocationIdentifier" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="DistrictSubDivisionIdentifier" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
      <Column Name="PostBoxIdentifier" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PostDistrictName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CareOfName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line4" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line5" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line6" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LocationDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CprData_Address" Member="CprData" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="CprData" IsForeignKey="true" />
      <Association Name="Municipality_Address" Member="Municipality" ThisKey="MunicipalityCode" OtherKey="MunicipalityCode" Type="Municipality" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Municipality" Member="Municipalities">
    <Type Name="Municipality">
      <Column Name="MunicipalityCode" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MunicipalityName" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Association Name="Municipality_Address" Member="Addresses" ThisKey="MunicipalityCode" OtherKey="MunicipalityCode" Type="Address" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="UUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserInterfaceKeyText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Person_PersonRegistration" Member="PersonRegistrations" ThisKey="UUID" OtherKey="UUID" Type="PersonRegistration" />
    </Type>
  </Table>
  <Table Name="dbo.Effect" Member="Effects">
    <Type Name="Effect">
      <Column Name="EffectId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActorText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CommentText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Effect_PersonRelationship" Member="PersonRelationships" ThisKey="EffectId" OtherKey="EffectId" Type="PersonRelationship" />
      <Association Name="Effect_PersonAttribute" Member="PersonAttributes" ThisKey="EffectId" OtherKey="EffectId" Type="PersonAttribute" />
      <Association Name="Effect_PersonRegistration" Member="PersonRegistrations" ThisKey="EffectId" OtherKey="EffectId" Type="PersonRegistration" />
    </Type>
  </Table>
  <Table Name="dbo.RelationshipType" Member="RelationshipTypes">
    <Type Name="RelationshipType">
      <Column Name="RelationshipTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ForwardName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RelationshipType_PersonRelationship" Member="PersonRelationships" ThisKey="RelationshipTypeId" OtherKey="RelationshipTypeId" Type="PersonRelationship" />
    </Type>
  </Table>
  <Table Name="dbo.PersonRelationship" Member="PersonRelationships">
    <Type Name="PersonRelationship">
      <Column Name="PersonRelationshipId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RelatedPersonUuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RelationshipTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommentText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EffectId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="RelationshipType_PersonRelationship" Member="RelationshipType" ThisKey="RelationshipTypeId" OtherKey="RelationshipTypeId" Type="RelationshipType" IsForeignKey="true" />
      <Association Name="Effect_PersonRelationship" Member="Effect" ThisKey="EffectId" OtherKey="EffectId" Type="Effect" IsForeignKey="true" />
      <Association Name="PersonRegistration_PersonRelationship" Member="PersonRegistration" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonAttributes" Member="PersonAttributes">
    <Type Name="PersonAttribute">
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GenderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BirthdateUncertainty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EffectId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="PersonAttribute_ForeignCitizenData" Member="ForeignCitizenData" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="ForeignCitizenData" Cardinality="One" />
      <Association Name="PersonAttribute_UnknownCitizenData" Member="UnknownCitizenData" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="UnknownCitizenData" Cardinality="One" />
      <Association Name="PersonAttribute_CprData" Member="CprData" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="CprData" Cardinality="One" />
      <Association Name="Effect_PersonAttribute" Member="Effect" ThisKey="EffectId" OtherKey="EffectId" Type="Effect" IsForeignKey="true" />
      <Association Name="Gender_PersonAttribute" Member="Gender" ThisKey="GenderId" OtherKey="GenderId" Type="Gender" IsForeignKey="true" />
      <Association Name="PersonRegistration_PersonAttribute" Member="PersonRegistration" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LifecycleStatus" Member="LifecycleStatus">
    <Type Name="LifecycleStatus">
      <Column Name="LifecycleStatusId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LifecycleStatusName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LifecycleStatus_PersonRegistration" Member="PersonRegistrations" ThisKey="LifecycleStatusId" OtherKey="LifecycleStatusId" Type="PersonRegistration" />
    </Type>
  </Table>
  <Table Name="dbo.PersonRegistration" Member="PersonRegistrations">
    <Type Name="PersonRegistration">
      <Column Name="PersonRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ActorText" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BrokerUpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CommentText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LifecycleStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EffectId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="PersonRegistration_PersonState" Member="PersonState" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonState" Cardinality="One" />
      <Association Name="PersonRegistration_PersonRelationship" Member="PersonRelationships" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonRelationship" />
      <Association Name="PersonRegistration_PersonAttribute" Member="PersonAttribute" ThisKey="PersonRegistrationId" OtherKey="PersonRegistrationId" Type="PersonAttribute" Cardinality="One" />
      <Association Name="Effect_PersonRegistration" Member="Effect" ThisKey="EffectId" OtherKey="EffectId" Type="Effect" IsForeignKey="true" />
      <Association Name="LifecycleStatus_PersonRegistration" Member="LifecycleStatus" ThisKey="LifecycleStatusId" OtherKey="LifecycleStatusId" Type="LifecycleStatus" IsForeignKey="true" />
      <Association Name="Person_PersonRegistration" Member="Person" ThisKey="UUID" OtherKey="UUID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
</Database>