<?xml version="1.0" encoding="utf-8"?><Database Name="DPR7" Class="UpdatesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.T_DPRUpdateStaging" Member="T_DPRUpdateStagings">
    <Type Name="T_DPRUpdateStaging">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PNR" Type="System.Decimal" DbType="Decimal(11,0) NOT NULL" CanBeNull="false" />
      <Column Name="DPRTable" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="CreateTS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_DPRUpdateStaging_DPRTable" Member="T_DPRUpdateStaging_DPRTables">
    <Type Name="T_DPRUpdateStaging_DPRTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DPRTable" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>