// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 2.1.3314.24787
//    <NameSpace>CPRBroker.Schemas</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><DisableDebug>True</DisableDebug><CustomUsings></CustomUsings>
//  <auto-generated>
// ------------------------------------------------------------------------------
namespace CPRBroker.Schemas
{
    using System.ComponentModel;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    [System.Xml.Serialization.XmlRootAttribute("PersonBasicStructure", Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/", IsNullable = false)]
    public partial class PersonBasicStructureType
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private RegularCPRPersonType regularCPRPersonField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private MaritalStatusCodeType maritalStatusCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private PersonDeathDateStructureType personDeathDateStructureField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string personNationalityCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private AddressIdentifierCodeType addressIdentifierCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool addressIdentifierCodeFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private object itemField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool personInformationProtectionIndicatorField;

        public PersonBasicStructureType()
        {
            if ((this.personDeathDateStructureField == null))
            {
                this.personDeathDateStructureField = new PersonDeathDateStructureType();
            }
            if ((this.regularCPRPersonField == null))
            {
                this.regularCPRPersonField = new RegularCPRPersonType();
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/01/17/")]
        public RegularCPRPersonType RegularCPRPerson
        {
            get
            {
                return this.regularCPRPersonField;
            }
            set
            {
                this.regularCPRPersonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/09/19/")]
        public MaritalStatusCodeType MaritalStatusCode
        {
            get
            {
                return this.maritalStatusCodeField;
            }
            set
            {
                this.maritalStatusCodeField = value;
            }
        }

        /// <remarks/>
        public PersonDeathDateStructureType PersonDeathDateStructure
        {
            get
            {
                return this.personDeathDateStructureField;
            }
            set
            {
                this.personDeathDateStructureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string PersonNationalityCode
        {
            get
            {
                return this.personNationalityCodeField;
            }
            set
            {
                this.personNationalityCodeField = value;
            }
        }

        /// <remarks/>
        public AddressIdentifierCodeType AddressIdentifierCode
        {
            get
            {
                return this.addressIdentifierCodeField;
            }
            set
            {
                this.addressIdentifierCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressIdentifierCodeSpecified
        {
            get
            {
                return this.addressIdentifierCodeFieldSpecified;
            }
            set
            {
                this.addressIdentifierCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DanishAddressStructure", typeof(DanishAddressStructureType))]
        [System.Xml.Serialization.XmlElementAttribute("ForeignAddressStructure", typeof(ForeignAddressStructureType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
        public bool PersonInformationProtectionIndicator
        {
            get
            {
                return this.personInformationProtectionIndicatorField;
            }
            set
            {
                this.personInformationProtectionIndicatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/01/17/")]
    public partial class RegularCPRPersonType
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private SimpleCPRPersonType simpleCPRPersonField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string personNameForAddressingNameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private PersonGenderCodeType personGenderCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool personInformationProtectionIndicatorField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private PersonBirthDateStructureType personBirthDateStructureField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private PersonCivilRegistrationStatusStructureType personCivilRegistrationStatusStructureField;

        public RegularCPRPersonType()
        {
            if ((this.personCivilRegistrationStatusStructureField == null))
            {
                this.personCivilRegistrationStatusStructureField = new PersonCivilRegistrationStatusStructureType();
            }
            if ((this.personBirthDateStructureField == null))
            {
                this.personBirthDateStructureField = new PersonBirthDateStructureType();
            }
            if ((this.simpleCPRPersonField == null))
            {
                this.simpleCPRPersonField = new SimpleCPRPersonType();
            }
        }

        /// <remarks/>
        public SimpleCPRPersonType SimpleCPRPerson
        {
            get
            {
                return this.simpleCPRPersonField;
            }
            set
            {
                this.simpleCPRPersonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/itst.dk/xml/schemas/2005/02/22/")]
        public string PersonNameForAddressingName
        {
            get
            {
                return this.personNameForAddressingNameField;
            }
            set
            {
                this.personNameForAddressingNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public PersonGenderCodeType PersonGenderCode
        {
            get
            {
                return this.personGenderCodeField;
            }
            set
            {
                this.personGenderCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
        public bool PersonInformationProtectionIndicator
        {
            get
            {
                return this.personInformationProtectionIndicatorField;
            }
            set
            {
                this.personInformationProtectionIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
        public PersonBirthDateStructureType PersonBirthDateStructure
        {
            get
            {
                return this.personBirthDateStructureField;
            }
            set
            {
                this.personBirthDateStructureField = value;
            }
        }

        /// <remarks/>
        public PersonCivilRegistrationStatusStructureType PersonCivilRegistrationStatusStructure
        {
            get
            {
                return this.personCivilRegistrationStatusStructureField;
            }
            set
            {
                this.personCivilRegistrationStatusStructureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum PersonGenderCodeType
    {

        /// <remarks/>
        male,

        /// <remarks/>
        female,

        /// <remarks/>
        unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
    public partial class PersonBirthDateStructureType
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime birthDateField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool birthDateUncertaintyIndicatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", DataType = "date")]
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        public bool BirthDateUncertaintyIndicator
        {
            get
            {
                return this.birthDateUncertaintyIndicatorField;
            }
            set
            {
                this.birthDateUncertaintyIndicatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/01/17/")]
    public partial class PersonCivilRegistrationStatusStructureType
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private PersonCivilRegistrationStatusCodeType personCivilRegistrationStatusCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime personCivilRegistrationStatusStartDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
        public PersonCivilRegistrationStatusCodeType PersonCivilRegistrationStatusCode
        {
            get
            {
                return this.personCivilRegistrationStatusCodeField;
            }
            set
            {
                this.personCivilRegistrationStatusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime PersonCivilRegistrationStatusStartDate
        {
            get
            {
                return this.personCivilRegistrationStatusStartDateField;
            }
            set
            {
                this.personCivilRegistrationStatusStartDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
    public enum PersonCivilRegistrationStatusCodeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("90")]
        Item90,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/09/19/")]
    public enum MaritalStatusCodeType
    {

        /// <remarks/>
        married,

        /// <remarks/>
        divorced,

        /// <remarks/>
        widow,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registered partnership")]
        registeredpartnership,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("abolition of registrered partnership")]
        abolitionofregistreredpartnership,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("longest living partner")]
        longestlivingpartner,

        /// <remarks/>
        deceased,

        /// <remarks/>
        unmarried,
    }
}
